import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {C} from './scenes/buffett/Shared';
import {RETIREMENT_CAPTIONS} from './retirementCaptions';

const FONT = '"PingFang SC", "Noto Sans CJK SC", "Microsoft YaHei", Arial, sans-serif';
const FPS = 30;
const TOTAL_FRAMES = 9685;

// Timings follow the paragraph structure of the supplied narration. The source
// has no subtitle file, so the visual changes are placed at section boundaries
// and held until the next complete thought finishes.
const SCENE_STARTS = [0, 513, 1110, 1860, 2280, 2715, 3300, 3900, 4500, 5250, 5715, 5901, 6720, 6900, 7680, 8535, 9180, 9390];
const SCENE_FRAMES = SCENE_STARTS.map((start, i) => i === SCENE_STARTS.length - 1 ? TOTAL_FRAMES - start : SCENE_STARTS[i + 1] - start);

const fade = (frame: number, delay = 0, duration = 18) => interpolate(frame, [delay, delay + duration], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic)});
const rise = (frame: number, delay = 0, distance = 26) => interpolate(frame, [delay, delay + 18], [distance, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic)});
const enter = (frame: number, delay = 0, distance = 26) => ({opacity: fade(frame, delay), transform: `translateY(${rise(frame, delay, distance)}px)`});

const Mark: React.FC<{children: React.ReactNode; color?: string}> = ({children, color = C.green}) => <span style={{position: 'relative', zIndex: 0, display: 'inline-block'}}><span style={{position: 'absolute', left: -9, right: -9, bottom: 5, height: 22, borderRadius: 7, background: color, zIndex: -1}} />{children}</span>;
const Panel: React.FC<{children: React.ReactNode; bg?: string; shadow?: string; style?: React.CSSProperties}> = ({children, bg = '#FFFDF7', shadow = `11px 13px 0 ${C.blue}`, style}) => <div style={{boxSizing: 'border-box', padding: '34px 40px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 28, boxShadow: shadow, ...style}}>{children}</div>;
const Chip: React.FC<{children: React.ReactNode; bg?: string; style?: React.CSSProperties}> = ({children, bg = C.green, style}) => <div style={{display: 'inline-block', padding: '13px 26px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 999, fontSize: 31, lineHeight: 1.1, fontWeight: 950, ...style}}>{children}</div>;
const Arrow: React.FC<{children?: React.ReactNode; color?: string}> = ({children = '→', color = C.orange}) => <div style={{fontSize: 78, lineHeight: 1, fontWeight: 950, color}}>{children}</div>;

type FrameProps = {page: number; kicker: string; accent?: string; title: React.ReactNode; subtitle?: React.ReactNode; titleSize?: number; children: React.ReactNode};
const Frame: React.FC<FrameProps> = ({page, kicker, accent = C.orange, title, subtitle, titleSize = 88, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', inset: 0, opacity: 0.72, backgroundImage: 'linear-gradient(rgba(24,24,24,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(24,24,24,0.08) 1px, transparent 1px)', backgroundSize: '48px 48px'}} />
    <div style={{position: 'absolute', left: -90, top: 330, width: 190, height: 190, border: `19px solid ${accent}`, borderRadius: 48, transform: 'rotate(-12deg)', opacity: 0.55}} />
    <div style={{position: 'absolute', right: -175, bottom: -210, width: 520, height: 520, borderRadius: '50%', background: accent, opacity: 0.68}} />
    <div style={{position: 'absolute', left: 126, top: 88, display: 'flex', alignItems: 'center', gap: 18, color: accent, fontSize: 31, fontWeight: 950, letterSpacing: 4, opacity: fade(frame, 0, 12)}}><span style={{display: 'inline-block', width: 52, height: 14, background: accent}} />{kicker}</div>
    <div style={{position: 'absolute', right: 126, top: 88, color: '#555', fontSize: 27, fontWeight: 900, letterSpacing: 4, opacity: fade(frame, 0, 12)}}>{String(page).padStart(2, '0')} / 18</div>
    <div style={{position: 'absolute', left: 126, right: 126, top: 166, opacity: fade(frame, 8, 18), transform: `translateY(${rise(frame, 8)}px)`}}>
      <div style={{fontSize: titleSize, lineHeight: 1.08, fontWeight: 950, letterSpacing: -4}}>{title}</div>
      {subtitle && <div style={{marginTop: 24, maxWidth: 1650, fontSize: 44, lineHeight: 1.25, color: C.gray, fontWeight: 800}}>{subtitle}</div>}
    </div>
    {children}
  </AbsoluteFill>;
};

const Content: React.FC<{children: React.ReactNode; style?: React.CSSProperties}> = ({children, style}) => <div style={{position: 'absolute', left: 126, right: 126, top: 430, bottom: 48, ...style}}>{children}</div>;
const PageSfx = () => <Audio src={staticFile('sfx/whoosh.mp3')} volume={0.36} />;
const MOTION_TIMES: Record<number, number[]> = {
  1: [20, 120], 2: [18, 110], 3: [20, 80, 140], 4: [18, 70, 122], 5: [18, 92], 6: [20, 82, 144], 7: [18, 64, 110, 156], 8: [20, 80, 140], 9: [18, 74, 130], 10: [20, 78, 135], 11: [18, 85, 150], 12: [18, 72, 126], 13: [18, 62, 106, 150], 14: [18, 54, 96, 138, 180], 15: [18, 84], 16: [18, 92], 17: [20, 110], 18: [18, 90], 19: [20],
};
const MotionSfx: React.FC<{at: number}> = ({at}) => <Sequence from={at} durationInFrames={28}><Audio src={staticFile('sfx/pop.mp3')} volume={0.195} /></Sequence>;
const SceneSfx: React.FC<{kind: number}> = ({kind}) => <>{(MOTION_TIMES[kind] ?? [20]).map((at) => <MotionSfx key={at} at={at} />)}</>;

const CaptionOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const timeMs = (frame / FPS) * 1000;
  const caption = RETIREMENT_CAPTIONS.find((item) => item.startMs <= timeMs && item.endMs > timeMs);
  if (!caption) return null;
  return <div style={{position: 'absolute', left: 180, right: 180, bottom: 34, display: 'flex', justifyContent: 'center', pointerEvents: 'none'}}>
    <div style={{maxWidth: 1500, padding: '13px 28px 15px', borderRadius: 16, background: 'rgba(24,24,24,0.86)', color: '#FFFDF7', border: `2px solid ${C.ink}`, boxShadow: `6px 7px 0 ${C.orange}`, fontSize: 37, lineHeight: 1.3, fontWeight: 850, textAlign: 'center', letterSpacing: 1}}>{caption.text}</div>
  </div>;
};

const MiniStat: React.FC<{value: string; label: string; bg?: string; color?: string}> = ({value, label, bg = '#FFFDF7', color = C.orange}) => <Panel bg={bg} shadow={`9px 11px 0 ${color}`} style={{height: 230, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 66, fontWeight: 950}}>{value}</div><div style={{marginTop: 14, fontSize: 32, color: C.gray, fontWeight: 850}}>{label}</div></Panel>;

const SceneVisual: React.FC<{kind: number; page: number}> = ({kind, page}) => {
  const frame = useCurrentFrame();
  const inView = (delay = 20, distance = 32) => enter(frame, delay, distance);

  if (kind === 1) return <Frame page={page} kicker="红利ETF · 退休计划" title={<>攒够100万，<br /><Mark color={C.orange}>全买红利ETF退休？</Mark></>} subtitle="先别急着辞职，先把三个问题算清楚。" titleSize={98}><Content style={{top: 470}}><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 42, ...inView(20)}}><Panel bg={C.paleOrange} shadow={`12px 14px 0 ${C.orange}`} style={{width: 760, height: 290, textAlign: 'center'}}><Chip bg={C.orange}>粉丝的计划</Chip><div style={{marginTop: 34, fontSize: 57, fontWeight: 950}}>100万 → 红利ETF</div><div style={{marginTop: 18, fontSize: 36, color: C.gray, fontWeight: 850}}>每月想拿 4000 多</div></Panel><Arrow /><Panel bg={C.paleGreen} shadow={`12px 14px 0 ${C.green}`} style={{width: 570, height: 290, textAlign: 'center'}}><div style={{fontSize: 76, fontWeight: 950}}>？</div><div style={{fontSize: 38, fontWeight: 900}}>真的够退休吗</div></Panel></div><div style={{marginTop: 48, textAlign: 'center', ...inView(120)}}><Chip bg={C.blue} style={{fontSize: 39}}>哈喽，我是剑平</Chip></div></Content></Frame>;

  if (kind === 2) return <Frame page={page} kicker="第一个问题" title={<>4000块，<Mark color={C.orange}>每个月都拿得到吗？</Mark></>} subtitle="5%的收益，不是银行利率。" titleSize={92}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 32, ...inView(18)}}><MiniStat value="100万" label="本金" bg={C.paleGreen} color={C.green} /><Arrow>→</Arrow><MiniStat value="5%" label="只是一个假设" bg={C.paleBlue} color={C.blue} /><Arrow>→</Arrow><MiniStat value="4167" label="平均每月" bg={C.paleOrange} color={C.orange} /></div><div style={{marginTop: 55, textAlign: 'center', ...inView(110)}}><Chip bg={C.orange} style={{fontSize: 40}}>听着没问题，但它会变化</Chip></div></Content></Frame>;

  if (kind === 3) { const rows = [['3%', '2500'], ['4%', '3300'], ['5%', '4167'], ['6%', '5000']]; return <Frame page={page} kicker="收益不是固定数字" title={<>同样100万，<Mark color={C.blue}>每月可能差一倍</Mark></>} subtitle="把四种收益假设放在一起，答案立刻变得诚实。" titleSize={90}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 24, ...inView(18)}}>{rows.map(([rate, cash], i) => <Panel key={rate} bg={i === 2 ? C.paleOrange : '#FFFDF7'} shadow={`9px 11px 0 ${[C.green, C.blue, C.orange, '#A879E8'][i]}`} style={{height: 310, textAlign: 'center', transform: `translateY(${Math.sin(frame / 15 + i) * 3}px)`}}><div style={{fontSize: 64, fontWeight: 950, color: [C.green, C.blue, C.orange, '#A879E8'][i]}}>{rate}</div><div style={{marginTop: 38, fontSize: 53, fontWeight: 950}}>¥{cash}</div><div style={{marginTop: 14, fontSize: 29, color: C.gray, fontWeight: 850}}>每月平均</div></Panel>)}</div><div style={{marginTop: 52, textAlign: 'center', ...inView(140)}}><Chip bg={C.green} style={{fontSize: 39}}>真正关键：5%不是固定数字</Chip></div></Content></Frame>; }

  if (kind === 4) return <Frame page={page} kicker="第二个问题" title={<>你有没有<Mark color={C.orange}>反过来算过？</Mark></>} subtitle="先算一年要花多少，再倒推需要多少本金。" titleSize={96}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 28, ...inView(18)}}><Panel bg={C.paleGreen} shadow={`11px 13px 0 ${C.green}`} style={{width: 650, height: 310, textAlign: 'center'}}><div style={{fontSize: 64, fontWeight: 950}}>¥3000 / 月</div><div style={{marginTop: 28, fontSize: 39, fontWeight: 900}}>一年 ¥36000</div><div style={{marginTop: 16, fontSize: 32, color: C.gray, fontWeight: 800}}>支出率 3.6%</div></Panel><Arrow>→</Arrow><Panel bg={C.paleOrange} shadow={`11px 13px 0 ${C.orange}`} style={{width: 650, height: 310, textAlign: 'center'}}><div style={{fontSize: 64, fontWeight: 950}}>¥5000 / 月</div><div style={{marginTop: 28, fontSize: 39, fontWeight: 900}}>一年 ¥60000</div><div style={{marginTop: 16, fontSize: 32, color: C.gray, fontWeight: 800}}>要重新倒推</div></Panel></div><div style={{marginTop: 52, textAlign: 'center', ...inView(100)}}><Chip bg={C.blue} style={{fontSize: 40}}>不是先问“收益多少”，而是先问“我会花多少”</Chip></div></Content></Frame>;

  if (kind === 5) { const rows = [['3%', '200万'], ['4%', '150万'], ['5%', '120万'], ['6%', '100万']]; return <Frame page={page} kicker="倒推本金" title={<>想花5000 / 月，<Mark color={C.orange}>100万够吗？</Mark></>} subtitle="只有6%的情景，100万才刚好够。" titleSize={88}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 24, ...inView(18)}}>{rows.map(([rate, principal], i) => <Panel key={rate} bg={i === 3 ? C.paleGreen : '#FFFDF7'} shadow={`9px 11px 0 ${i === 3 ? C.green : C.orange}`} style={{height: 315, textAlign: 'center'}}><div style={{fontSize: 48, fontWeight: 950, color: i === 3 ? C.green : C.orange}}>{rate}收益</div><div style={{marginTop: 40, fontSize: 58, fontWeight: 950}}>{principal}</div><div style={{marginTop: 18, fontSize: 28, color: C.gray, fontWeight: 850}}>需要本金</div></Panel>)}</div><div style={{marginTop: 50, textAlign: 'center', ...inView(92)}}><Chip bg={C.orange} style={{fontSize: 43}}>注意：刚刚够</Chip></div></Content></Frame>; }

  if (kind === 6) return <Frame page={page} kicker="刚刚够 = 没有缓冲" title={<>一分钱误差都没有，<Mark color={C.orange}>现实里很危险</Mark></>} subtitle="修车、换手机、空调罢工，都会让刚好的现金流塌掉。" titleSize={86}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 28, ...inView(20)}}><Panel bg={C.paleGreen} shadow={`11px 13px 0 ${C.green}`} style={{width: 620, height: 300, textAlign: 'center'}}><div style={{fontSize: 66, fontWeight: 950}}>¥5000</div><div style={{marginTop: 12, fontSize: 33, fontWeight: 850}}>每月现金流</div><div style={{marginTop: 28, fontSize: 28, color: C.gray, fontWeight: 800}}>刚刚够</div></Panel><Arrow>−</Arrow><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 22}}>{[['修车', '3000', C.orange], ['换手机', '6000', C.blue]].map(([label, value, color], i) => <Panel key={label} bg={i === 0 ? C.paleOrange : C.paleBlue} shadow={`8px 10px 0 ${color}`} style={{width: 300, height: 140, padding: '20px 25px', textAlign: 'center'}}><div style={{fontSize: 31, fontWeight: 950}}>{label}</div><div style={{fontSize: 36, fontWeight: 950}}>¥{value}</div></Panel>)}</div></div><div style={{marginTop: 55, textAlign: 'center', ...inView(125)}}><Chip bg={C.orange} style={{fontSize: 42}}>现金流不能只看平均数</Chip></div></Content></Frame>;

  if (kind === 7) { const rows = [['今天', '5000', C.green], ['10年后', '6095', C.blue], ['20年后', '7430', C.orange], ['30年后', '9057', '#A879E8']]; return <Frame page={page} kicker="第三个问题" title={<>20年、30年之后，<Mark color={C.blue}>4000块还值钱吗？</Mark></>} subtitle="按长期通胀2%估算，购买力会慢慢变薄。" titleSize={82}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 22, ...inView(18)}}>{rows.map(([label, value, color], i) => <Panel key={label} bg={i === 0 ? C.paleGreen : '#FFFDF7'} shadow={`9px 11px 0 ${color}`} style={{height: 300, textAlign: 'center'}}><div style={{fontSize: 34, fontWeight: 950, color}}>{label}</div><div style={{marginTop: 42, fontSize: 58, fontWeight: 950}}>¥{value}</div><div style={{marginTop: 16, fontSize: 27, color: C.gray, fontWeight: 800}}>需要的钱</div></Panel>)}</div><div style={{marginTop: 55, textAlign: 'center', ...inView(110)}}><Chip bg={C.blue} style={{fontSize: 38}}>不是预测，是看看购买力</Chip></div></Content></Frame>; }

  if (kind === 8) return <Frame page={page} kicker="两个容易忽略的事实" title={<>分红不是利息，<Mark color={C.orange}>股息率也不是承诺</Mark></>} subtitle="企业利润会变化，分红可能多、可能少，甚至可能不分。" titleSize={88}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 34, ...inView(18)}}><Panel bg={C.paleOrange} shadow={`11px 13px 0 ${C.orange}`} style={{width: 700, height: 330}}><Chip bg={C.orange}>事实 01</Chip><div style={{marginTop: 30, fontSize: 49, fontWeight: 950}}>分红来自利润</div><div style={{marginTop: 24, fontSize: 33, color: C.gray, fontWeight: 800}}>今年赚得多，可能多分；明年下滑，可能少分。</div></Panel><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 700, height: 330}}><Chip bg={C.blue}>事实 02</Chip><div style={{marginTop: 30, fontSize: 49, fontWeight: 950}}>5%不是固定到账</div><div style={{marginTop: 24, fontSize: 33, color: C.gray, fontWeight: 800}}>今天看到的比例，不代表未来20年。</div></Panel></div><div style={{marginTop: 56, textAlign: 'center', ...inView(105)}}><Chip bg={C.orange} style={{fontSize: 40}}>它和银行每年固定付5%是两码事</Chip></div></Content></Frame>;

  if (kind === 9) return <Frame page={page} kicker="指数 ≠ 基金到账" title={<>看到股息率，<Mark color={C.blue}>不等于每年收到同样现金</Mark></>} subtitle="分不分、分多少、什么时候分，要看基金合同和分红公告。" titleSize={80}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 38, ...inView(18)}}><Panel bg={C.paleGreen} shadow={`10px 12px 0 ${C.green}`} style={{width: 560, height: 270, textAlign: 'center'}}><div style={{fontSize: 58, fontWeight: 950}}>指数</div><div style={{marginTop: 24, fontSize: 33, fontWeight: 850}}>股息率参考</div></Panel><Arrow>≠</Arrow><Panel bg={C.paleBlue} shadow={`10px 12px 0 ${C.blue}`} style={{width: 560, height: 270, textAlign: 'center'}}><div style={{fontSize: 58, fontWeight: 950}}>ETF</div><div style={{marginTop: 24, fontSize: 33, fontWeight: 850}}>分红公告</div></Panel></div><div style={{marginTop: 58, display: 'flex', justifyContent: 'center', gap: 20, ...inView(74)}}>{['价格', '+', '分红', '=', '总回报'].map((x, i) => <div key={`${x}-${i}`} style={{fontSize: i % 2 ? 65 : 48, fontWeight: 950, color: i === 4 ? C.orange : C.ink}}>{x}</div>)}</div><div style={{marginTop: 38, textAlign: 'center', ...inView(130)}}><Chip bg={C.blue} style={{fontSize: 38}}>长期投资看总回报</Chip></div></Content></Frame>;

  if (kind === 10) return <Frame page={page} kicker="危险的退休计划" title={<>如果每月必须准时到账4167，<Mark color={C.orange}>这个计划非常脆弱</Mark></>} subtitle="晚一天房租都交不起，就没有给市场波动留下空间。" titleSize={78}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 25, ...inView(18)}}><Panel bg={C.paleGreen} shadow={`10px 12px 0 ${C.green}`} style={{width: 430, height: 250, textAlign: 'center'}}><div style={{fontSize: 55, fontWeight: 950}}>收益</div><div style={{marginTop: 24, fontSize: 34, fontWeight: 850}}>不确定</div></Panel><Arrow>→</Arrow><Panel bg={C.paleOrange} shadow={`10px 12px 0 ${C.orange}`} style={{width: 430, height: 250, textAlign: 'center'}}><div style={{fontSize: 55, fontWeight: 950}}>支出</div><div style={{marginTop: 24, fontSize: 34, fontWeight: 850}}>每月固定</div></Panel><Arrow>→</Arrow><Panel bg={C.paleBlue} shadow={`10px 12px 0 ${C.blue}`} style={{width: 430, height: 250, textAlign: 'center'}}><div style={{fontSize: 55, fontWeight: 950}}>结果</div><div style={{marginTop: 24, fontSize: 34, fontWeight: 850}}>现金流紧绷</div></Panel></div><div style={{marginTop: 60, textAlign: 'center', ...inView(120)}}><Chip bg={C.orange} style={{fontSize: 44}}>危险的不是红利，是没有缓冲</Chip></div></Content></Frame>;

  if (kind === 11) return <Frame page={page} kicker="红利没问题" title={<>100%全押、然后永远不工作，<Mark color={C.orange}>才是问题</Mark></>} subtitle="100万当然有用，关键是把它放进更稳的生活结构。" titleSize={88}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 50, ...inView(18)}}><div style={{fontSize: 90, fontWeight: 950, color: C.green}}>100万</div><Arrow>→</Arrow><div style={{fontSize: 74, fontWeight: 950}}>选择权</div></div><div style={{marginTop: 70, textAlign: 'center', ...inView(85)}}><Chip bg={C.green} style={{fontSize: 44}}>不是立刻退休，而是增加缓冲</Chip></div></Content></Frame>;

  if (kind === 12) return <Frame page={page} kicker="正确的做法" title={<>把钱分成<Mark color={C.green}>三桶</Mark></>} subtitle="让每一笔钱承担不同任务，市场差的时候也能继续生活。" titleSize={100}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 28, ...inView(18)}}>{[['01', '应急钱', '医疗 · 维修 · 突发', C.orange, C.paleOrange], ['02', '生活费', '未来3—5年', C.blue, C.paleBlue], ['03', '投资资产', '长期增长 · 现金流', C.green, C.paleGreen]].map(([n, title, body, color, bg]) => <Panel key={String(n)} bg={String(bg)} shadow={`10px 12px 0 ${color}`} style={{height: 340}}><div style={{fontSize: 58, fontWeight: 950, color: String(color)}}>{n}</div><div style={{marginTop: 30, fontSize: 49, fontWeight: 950}}>{title}</div><div style={{marginTop: 24, fontSize: 31, color: C.gray, fontWeight: 850}}>{body}</div></Panel>)}</div><div style={{marginTop: 55, textAlign: 'center', ...inView(126)}}><Chip bg={C.green} style={{fontSize: 39}}>红利可以放第三桶，但不必是唯一</Chip></div></Content></Frame>;

  if (kind === 13) return <Frame page={page} kicker="100万计划 · 先问自己" title={<>不要马上给答案，<Mark color={C.blue}>先问5个问题</Mark></>} subtitle="退休不是一道只看收益率的题。" titleSize={94}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 18, ...inView(18)}}>{[['01', '住房', C.green], ['02', '医保', C.blue], ['03', '收入', C.orange], ['04', '熊市', '#A879E8'], ['05', '年龄', C.green]].map(([n, t, color]) => <Panel key={String(n)} bg={t === '年龄' ? C.paleGreen : '#FFFDF7'} shadow={`8px 10px 0 ${color}`} style={{height: 300, padding: '26px 20px', textAlign: 'center', transform: `translateY(${Math.sin(frame / 14 + Number(n)) * 3}px)`}}><div style={{fontSize: 36, fontWeight: 950, color}}>{n}</div><div style={{marginTop: 42, fontSize: 39, fontWeight: 950}}>{t}</div></Panel>)}</div><div style={{marginTop: 54, textAlign: 'center', ...inView(150)}}><Chip bg={C.blue} style={{fontSize: 37}}>五个答案，决定100万到底够不够</Chip></div></Content></Frame>;

  if (kind === 14) { const items = [['有自住房？', '还交3000房租，肯定不够'], ['医保和保障够不够？', '退休最大的风险是医疗支出'], ['有没有其他收入？', '兼职 · 自媒体 · 养老金 · 房租'], ['熊市愿意降消费？', '市场差时，生活也要能继续'], ['你现在几岁？', '60岁和30岁的100万不是同一道题']]; return <Frame page={page} kicker="五个问题 · 逐个检查" title={<>100万够不够，<Mark color={C.orange}>取决于生活结构</Mark></>} subtitle="每个问题都比一个漂亮的5%更重要。" titleSize={84}><Content><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 22, ...inView(18)}}>{items.map(([title, body], i) => <Panel key={title} bg={i === 4 ? C.paleOrange : i % 2 ? C.paleBlue : C.paleGreen} shadow={`8px 10px 0 ${i === 4 ? C.orange : i % 2 ? C.blue : C.green}`} style={{height: 210, opacity: fade(frame, i * 25, 14), transform: `translateY(${rise(frame, i * 25)}px)`}}><div style={{fontSize: 39, fontWeight: 950}}>{title}</div><div style={{marginTop: 22, fontSize: 29, color: C.gray, fontWeight: 800}}>{body}</div></Panel>)}</div></Content></Frame>; }

  if (kind === 15) return <Frame page={page} kicker="回到标题" title={<>攒够100万，<Mark color={C.orange}>全买红利ETF不上班？</Mark></>} subtitle="有可能，但条件比很多人想象的苛刻。" titleSize={83}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 26, ...inView(18)}}>{[['自住房', C.green], ['没负债', C.blue], ['低成本', C.orange], ['有保障', '#A879E8'], ['能调整消费', C.green]].map(([x, color], i) => <Panel key={String(x)} bg={i % 2 ? C.paleBlue : C.paleGreen} shadow={`8px 10px 0 ${color}`} style={{width: 260, height: 220, padding: '30px 20px', display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center'}}><div style={{fontSize: 34, fontWeight: 950}}>{x}</div></Panel>)}</div><div style={{marginTop: 70, textAlign: 'center', ...inView(84)}}><Chip bg={C.orange} style={{fontSize: 43}}>条件越多，计划越稳</Chip></div></Content></Frame>;

  if (kind === 16) return <Frame page={page} kicker="100万的价值" title={<>不是让你立刻退休，<Mark color={C.green}>而是给你选择权</Mark></>} subtitle="资产替你扛住一部分生活费，你就不必被一份烂工作绑住。" titleSize={88}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 28, ...inView(18)}}>{[['赚1万', '也许只需赚3000', C.orange, C.paleOrange], ['不能停', '现在可以休息半年', C.blue, C.paleBlue], ['必须忍', '可以问：值不值得？', C.green, C.paleGreen]].map(([before, after, color, bg]) => <Panel key={String(before)} bg={String(bg)} shadow={`10px 12px 0 ${color}`} style={{height: 350, textAlign: 'center'}}><div style={{fontSize: 40, color: C.gray, fontWeight: 850, textDecoration: 'line-through'}}>{before}</div><div style={{fontSize: 66, color: String(color), fontWeight: 950, margin: '30px 0'}}>→</div><div style={{fontSize: 40, fontWeight: 950}}>{after}</div></Panel>)}</div></Content></Frame>;

  if (kind === 17) return <Frame page={page} kicker="真正的答案" title={<>100万真正能给普通人的东西：<br /><Mark color={C.orange}>不是退休，是选择权。</Mark></>} subtitle="它让你第一次有底气拒绝一份不值得的工作。" titleSize={82}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 54, ...inView(20)}}><div style={{fontSize: 115, fontWeight: 950, color: C.orange}}>100万</div><Arrow color={C.green}>→</Arrow><Panel bg={C.paleGreen} shadow={`12px 14px 0 ${C.green}`} style={{width: 720, height: 300, display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center'}}><div style={{fontSize: 70, fontWeight: 950}}>选择权</div></Panel></div><div style={{marginTop: 60, textAlign: 'center', ...inView(110)}}><Chip bg={C.blue} style={{fontSize: 39}}>不被迫做决定，本身就是财富</Chip></div></Content></Frame>;

  if (kind === 18) return <Frame page={page} kicker="最后问你一个问题" title={<>如果是你，<Mark color={C.blue}>敢不敢辞职？</Mark></>} subtitle="没有房贷没有负债，每月大概4000块现金流，你会怎么选？" titleSize={98}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 30, ...inView(18)}}><Panel bg={C.paleGreen} shadow={`11px 13px 0 ${C.green}`} style={{width: 500, height: 280, textAlign: 'center'}}><div style={{fontSize: 68, fontWeight: 950}}>敢</div><div style={{marginTop: 18, fontSize: 33, color: C.gray, fontWeight: 800}}>先算清楚，再行动</div></Panel><Panel bg={C.paleOrange} shadow={`11px 13px 0 ${C.orange}`} style={{width: 500, height: 280, textAlign: 'center'}}><div style={{fontSize: 68, fontWeight: 950}}>不敢</div><div style={{marginTop: 18, fontSize: 33, color: C.gray, fontWeight: 800}}>继续积累选择权</div></Panel></div><div style={{marginTop: 68, textAlign: 'center', ...inView(90)}}><Chip bg={C.orange} style={{fontSize: 42}}>先把生活过稳，再谈退休</Chip></div></Content></Frame>;

  return <Frame page={page} kicker="红利ETF · 退休计划" title={<>100万的答案，<Mark color={C.green}>从来不只是收益率</Mark></>} subtitle="它是一套能否持续的生活系统。" titleSize={93}><Content><div style={{textAlign: 'center', ...inView(20)}}><div style={{fontSize: 92, fontWeight: 950}}>先算支出</div><div style={{fontSize: 70, color: C.orange, fontWeight: 950, margin: '28px 0'}}>↓</div><div style={{fontSize: 92, fontWeight: 950}}>再分三桶</div><div style={{fontSize: 70, color: C.green, fontWeight: 950, margin: '28px 0'}}>↓</div><Chip bg={C.green} style={{fontSize: 43}}>最后才决定投多少红利</Chip></div></Content></Frame>;
};

const SCENE_KINDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];
export const DividendRetirementVideo: React.FC = () => <AbsoluteFill style={{background: C.paper}}><Audio src={staticFile('retirement-dividend-etf.mp3')} /><Sequence from={0} durationInFrames={TOTAL_FRAMES} layout="none">{SCENE_STARTS.map((start, index) => <Sequence key={start} from={start} durationInFrames={SCENE_FRAMES[index]} layout="none"><PageSfx /><SceneSfx kind={SCENE_KINDS[index]} /><SceneVisual kind={SCENE_KINDS[index]} page={index + 1} /></Sequence>)}</Sequence><CaptionOverlay /></AbsoluteFill>;
