import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {ETF_EXPLAINER_CAPTIONS} from './etfExplainerCaptions';
import {ETF_EXPLAINER_SCENE_STARTS} from './etfExplainerSceneStarts';

const C = {
  ink: '#151515',
  yellow: '#fdca17',
  blue: '#1e50a2',
  cream: '#fff2df',
  gray: '#626262',
  paleBlue: '#dce8fb',
  paleYellow: '#ffe38a',
  white: '#fffaf2',
  pink: '#f7a6be',
};
const FONT = '"PingFang SC", "Noto Sans CJK SC", "Microsoft YaHei", Arial, sans-serif';
const FPS = 30;
const TOTAL_FRAMES = 12424;
const PAGE_COUNT = ETF_EXPLAINER_SCENE_STARTS.length;
const SCENE_START_FRAMES = ETF_EXPLAINER_SCENE_STARTS.map((value) => Math.round(value * FPS));
const SCENE_FRAMES = SCENE_START_FRAMES.map((start, index) => index === SCENE_START_FRAMES.length - 1 ? TOTAL_FRAMES - start : SCENE_START_FRAMES[index + 1] - start);

const ease = Easing.bezier(0.16, 1, 0.3, 1);
const fade = (frame: number, delay = 0, duration = 18) => interpolate(frame, [delay, delay + duration], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: ease});
const rise = (frame: number, delay = 0, distance = 32) => interpolate(frame, [delay, delay + 18], [distance, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: ease});
const enter = (frame: number, delay = 0, distance = 32) => ({opacity: fade(frame, delay), translate: `0px ${rise(frame, delay, distance)}px`});

const Mark: React.FC<{children: React.ReactNode; color?: string}> = ({children, color = C.yellow}) => (
  <span style={{position: 'relative', display: 'inline-block', zIndex: 0}}>
    <span style={{position: 'absolute', left: -10, right: -10, bottom: 7, height: 24, borderRadius: 5, background: color, zIndex: -1}} />
    {children}
  </span>
);

const Panel: React.FC<{children: React.ReactNode; bg?: string; shadow?: string; style?: React.CSSProperties}> = ({children, bg = C.white, shadow = `11px 13px 0 ${C.blue}`, style}) => (
  <div style={{boxSizing: 'border-box', padding: '30px 36px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 28, boxShadow: shadow, ...style}}>{children}</div>
);

const Pill: React.FC<{children: React.ReactNode; bg?: string; color?: string; style?: React.CSSProperties}> = ({children, bg = C.yellow, color = C.ink, style}) => (
  <div style={{display: 'inline-block', padding: '13px 27px', background: bg, color, border: `3px solid ${C.ink}`, borderRadius: 999, fontSize: 31, fontWeight: 950, lineHeight: 1.05, ...style}}>{children}</div>
);

const Arrow: React.FC<{children?: React.ReactNode; color?: string; size?: number}> = ({children = '→', color = C.blue, size = 76}) => (
  <div style={{fontSize: size, lineHeight: 1, fontWeight: 950, color}}>{children}</div>
);

const Frame: React.FC<{page: number; kicker: string; title: React.ReactNode; subtitle?: React.ReactNode; accent?: string; titleSize?: number; children: React.ReactNode}> = ({page, kicker, title, subtitle, accent = C.blue, titleSize = 86, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background: C.cream, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', inset: 0, opacity: 0.58, backgroundImage: 'linear-gradient(rgba(21,21,21,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(21,21,21,0.08) 1px, transparent 1px)', backgroundSize: '48px 48px'}} />
    <div style={{position: 'absolute', left: -100, top: 350, width: 210, height: 210, border: `20px solid ${accent}`, borderRadius: 48, rotate: '-12deg', opacity: 0.48}} />
    <div style={{position: 'absolute', right: -170, bottom: -230, width: 540, height: 540, borderRadius: '50%', background: accent, opacity: 0.70}} />
    <div style={{position: 'absolute', left: 126, top: 82, display: 'flex', alignItems: 'center', gap: 18, color: accent, fontSize: 31, fontWeight: 950, letterSpacing: 4, opacity: fade(frame)}}><span style={{display: 'inline-block', width: 54, height: 14, background: accent}} />{kicker}</div>
    <div style={{position: 'absolute', right: 126, top: 80, color: C.gray, fontSize: 27, fontWeight: 900, letterSpacing: 4, opacity: fade(frame)}}>{String(page).padStart(2, '0')} / {String(PAGE_COUNT).padStart(2, '0')}</div>
    <div style={{position: 'absolute', left: 126, right: 126, top: 164, ...enter(frame, 5)}}>
      <div style={{fontSize: titleSize, lineHeight: 1.08, fontWeight: 950, letterSpacing: -4}}>{title}</div>
      {subtitle && <div style={{marginTop: 20, fontSize: 43, lineHeight: 1.24, color: C.gray, fontWeight: 850}}>{subtitle}</div>}
    </div>
    {children}
  </AbsoluteFill>;
};

const Content: React.FC<{children: React.ReactNode; style?: React.CSSProperties}> = ({children, style}) => <div style={{position: 'absolute', left: 126, right: 126, top: 410, bottom: 46, ...style}}>{children}</div>;

const PageSfx = () => <Audio src={staticFile('sfx/whoosh.mp3')} volume={0.36} />;
const MOTION_TIMES: Record<number, number[]> = {
  1: [20, 110, 190], 2: [18, 100, 175], 3: [18, 105, 185], 4: [18, 105], 5: [18, 95, 170],
  6: [18, 100, 180], 7: [18, 100, 180], 8: [18, 85, 150, 215], 9: [18, 95, 170], 10: [18, 100, 180],
  11: [18, 100, 180], 12: [18, 90, 155, 220], 13: [18, 90, 160], 14: [18, 95, 170], 15: [18, 90, 160],
  16: [18, 100, 180], 17: [18, 100, 185], 18: [18, 105, 190], 19: [18, 100, 180], 20: [18, 95, 170], 21: [18, 105, 200],
};
const MotionSfx: React.FC<{at: number}> = ({at}) => <Sequence from={at} durationInFrames={28}><Audio src={staticFile('sfx/pop.mp3')} volume={0.10} /></Sequence>;
const SceneSfx: React.FC<{kind: number}> = ({kind}) => <>{(MOTION_TIMES[kind] ?? [20]).map((at) => <MotionSfx key={at} at={at} />)}</>;

const CaptionOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const timeMs = frame / FPS * 1000;
  const caption = ETF_EXPLAINER_CAPTIONS.find((item) => item.startMs <= timeMs && item.endMs > timeMs);
  if (!caption) return null;
  return <div style={{position: 'absolute', left: 150, right: 150, bottom: 25, display: 'flex', justifyContent: 'center', pointerEvents: 'none'}}><div style={{maxWidth: 1650, padding: '12px 28px 14px', borderRadius: 16, background: 'rgba(21,21,21,0.92)', color: C.cream, border: `2px solid ${C.ink}`, boxShadow: `6px 7px 0 ${C.yellow}`, fontSize: 37, lineHeight: 1.3, fontWeight: 850, textAlign: 'center', letterSpacing: 1}}>{caption.text}</div></div>;
};

const Step: React.FC<{number: string; title: string; desc: string; color?: string; bg?: string; style?: React.CSSProperties}> = ({number, title, desc, color = C.blue, bg = C.white, style}) => (
  <Panel bg={bg} shadow={`9px 11px 0 ${color}`} style={{height: 250, padding: '24px 28px', ...style}}>
    <div style={{display: 'flex', alignItems: 'center', gap: 18}}><div style={{width: 55, height: 55, borderRadius: '50%', background: color, color: bg === C.paleBlue ? C.cream : C.ink, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 29, fontWeight: 950}}>{number}</div><div style={{fontSize: 35, fontWeight: 950}}>{title}</div></div>
    <div style={{marginTop: 24, fontSize: 31, color: C.gray, lineHeight: 1.3, fontWeight: 850}}>{desc}</div>
  </Panel>
);

const LineChart: React.FC<{frame: number; matching?: boolean; color?: string}> = ({frame, matching = false, color = C.blue}) => {
  const second = matching ? '0,205 120,180 240,196 360,130 480,150 600,92 720,112 860,42' : '0,205 120,180 240,196 360,130 480,150 600,92 720,112 860,42';
  return <svg width="100%" height="290" viewBox="0 0 860 290" preserveAspectRatio="none" style={{overflow: 'visible'}}>
    <path d="M0 250 H860" stroke={C.ink} strokeWidth="4" opacity="0.35" />
    <path d="M0 150 H860" stroke={C.ink} strokeWidth="2" strokeDasharray="8 12" opacity="0.18" />
    <polyline points="0,225 120,204 240,220 360,160 480,178 600,124 720,140 860,76" fill="none" stroke={color} strokeWidth="13" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="1300 1300" strokeDashoffset={interpolate(frame, [12, 58], [1300, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})} />
    {matching && <polyline points={second} fill="none" stroke={C.yellow} strokeWidth="11" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="1300 1300" strokeDashoffset={interpolate(frame, [34, 78], [1300, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})} />}
    <circle cx="860" cy={matching ? 42 : 76} r="14" fill={C.yellow} stroke={C.ink} strokeWidth="4" />
  </svg>;
};

const SceneVisual: React.FC<{kind: number; page: number}> = ({kind, page}) => {
  const frame = useCurrentFrame();
  const inView = (delay = 18, distance = 32) => enter(frame, delay, distance);
  if (kind === 1) return <Frame page={page} kicker="ETF 入门 · 从零开始" title={<>ETF 到底是个啥？<br /><Mark color={C.yellow}>这期一次讲清楚</Mark></>} subtitle="避开金融黑话，把它变成你手上趁手的理财工具。" accent={C.blue} titleSize={101}><Content style={{top: 468}}><div style={{display: 'flex', justifyContent: 'center', gap: 26, ...inView(18)}}><Pill bg={C.paleBlue} style={{fontSize: 43}}>宽基ETF +30%</Pill><Pill bg={C.paleYellow} style={{fontSize: 43}}>芯片ETF +80%</Pill></div><div style={{marginTop: 70, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 38, ...inView(110)}}><div style={{fontSize: 64, fontWeight: 950}}>炒股不如买 ETF？</div><Arrow color={C.yellow} /><div style={{fontSize: 54, color: C.blue, fontWeight: 950}}>先搞懂再出手</div></div></Content></Frame>;

  if (kind === 2) return <Frame page={page} kicker="为什么总是记不住" title={<>知识太零碎，<Mark color={C.yellow}>自然串不起来</Mark></>} subtitle="短视频、短文章、金融黑话，信息很多，框架很少。" accent={C.yellow} titleSize={92}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 26, ...inView(18)}}>{[['短视频', C.paleBlue, C.blue], ['短文章', C.paleYellow, C.yellow], ['金融黑话', C.pink, C.blue]].map(([text, bg, color], i) => <Panel key={String(text)} bg={String(bg)} shadow={`9px 11px 0 ${String(color)}`} style={{width: 360, height: 210, textAlign: 'center', paddingTop: 65, opacity: fade(frame, i * 28, 16), translate: `0px ${rise(frame, i * 28)}px`}}><div style={{fontSize: 43, fontWeight: 950}}>{text}</div></Panel>)}</div><div style={{margin: '60px auto 0', width: 760, textAlign: 'center', ...inView(120)}}><Panel bg={C.white} shadow={`11px 13px 0 ${C.blue}`} style={{height: 170, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 24}}><div style={{fontSize: 48, fontWeight: 950}}>碎片</div><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 48, color: C.blue, fontWeight: 950}}>完整认知</div></Panel></div></Content></Frame>;

  if (kind === 3) return <Frame page={page} kicker="本期目标" title={<>搭一套从零到一的<Mark color={C.yellow}>ETF 攻略</Mark></>} subtitle="看完以后，你知道它是什么，也知道怎么用。" accent={C.blue} titleSize={93}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 22, ...inView(18)}}><Step number="01" title="拆黑话" desc="ETF 的名字，拆成两个部分" color={C.blue} bg={C.paleBlue} style={{width: 385}} /><Arrow color={C.yellow} /><Step number="02" title="建框架" desc="指数、权重、交易方式" color={C.yellow} bg={C.paleYellow} style={{width: 385}} /><Arrow color={C.yellow} /><Step number="03" title="会选择" desc="场内还是场外，按需求选" color={C.blue} bg={C.white} style={{width: 385}} /></div><div style={{marginTop: 65, textAlign: 'center', ...inView(135)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 41}}>从听说过 ETF → 真正会用 ETF</Pill></div></Content></Frame>;

  if (kind === 4) return <Frame page={page} kicker="先解决最核心的问题" title={<>ETF，本质上是一个<Mark color={C.yellow}>跟指数的工具</Mark></>} subtitle="你看好哪个指数或板块，就买对应的 ETF。" accent={C.yellow} titleSize={90}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 25, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`10px 12px 0 ${C.blue}`} style={{width: 450, height: 255, textAlign: 'center'}}><div style={{fontSize: 50, fontWeight: 950}}>市场指数</div><div style={{marginTop: 20, fontSize: 31, color: C.gray, fontWeight: 850}}>你想跟上的走势</div></Panel><Arrow color={C.yellow} /><Panel bg={C.paleYellow} shadow={`10px 12px 0 ${C.yellow}`} style={{width: 490, height: 255, textAlign: 'center'}}><div style={{fontSize: 69, color: C.blue, fontWeight: 950}}>ETF</div><div style={{marginTop: 10, fontSize: 31, color: C.gray, fontWeight: 850}}>把指数变成可买的工具</div></Panel><Arrow color={C.yellow} /><Panel bg={C.white} shadow={`10px 12px 0 ${C.blue}`} style={{width: 360, height: 255, textAlign: 'center'}}><div style={{fontSize: 50, fontWeight: 950}}>你</div><div style={{marginTop: 20, fontSize: 31, color: C.gray, fontWeight: 850}}>买入持有</div></Panel></div><div style={{marginTop: 65, textAlign: 'center', ...inView(120)}}><Pill bg={C.yellow} style={{fontSize: 41}}>答案，其实藏在名字里</Pill></div></Content></Frame>;

  if (kind === 5) return <Frame page={page} kicker="ETF 是三个英文单词" title={<>名字很长，<Mark color={C.yellow}>拆开就简单</Mark></>} subtitle="Exchange Traded Fund = 交易型开放式指数基金。" accent={C.blue} titleSize={95}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 28, ...inView(18)}}>{[['Exchange', '交易型', C.paleBlue, C.blue], ['Traded', '可交易', C.paleYellow, C.yellow], ['Fund', '基金', C.pink, C.blue]].map(([en, zh, bg, color], i) => <Panel key={String(en)} bg={String(bg)} shadow={`10px 12px 0 ${String(color)}`} style={{width: 420, height: 290, textAlign: 'center', opacity: fade(frame, i * 32, 16), translate: `0px ${rise(frame, i * 32)}px`}}><div style={{fontSize: 50, fontWeight: 950, color: C.blue}}>{en}</div><div style={{height: 4, background: String(color), margin: '30px 30px 26px'}} /><div style={{fontSize: 52, fontWeight: 950}}>{zh}</div></Panel>)}</div><div style={{marginTop: 58, textAlign: 'center', ...inView(125)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 42}}>先记住：它是能交易的指数基金</Pill></div></Content></Frame>;

  if (kind === 6) return <Frame page={page} kicker="第一点 · 什么是指数" title={<>指数，像一盒<Mark color={C.yellow}>代表性点心</Mark></>} subtitle="不用每种都买，先把最有代表性的装进一个礼盒。" accent={C.yellow} titleSize={91}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 30, ...inView(18)}}><Panel bg={C.white} shadow={`10px 12px 0 ${C.blue}`} style={{width: 480, height: 355, textAlign: 'center'}}><div style={{fontSize: 45, fontWeight: 950}}>点心铺</div><div style={{display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 14, marginTop: 32, padding: '0 25px'}}>{['🥮', '🍪', '🍰', '🥠', '🍡', '🍩'].map((x) => <div key={x} style={{fontSize: 44, background: C.paleYellow, borderRadius: 14, padding: 8}}>{x}</div>)}</div></Panel><Arrow color={C.yellow} size={92}>→</Arrow><Panel bg={C.paleYellow} shadow={`10px 12px 0 ${C.yellow}`} style={{width: 620, height: 355, textAlign: 'center'}}><div style={{fontSize: 45, fontWeight: 950}}>指数礼盒</div><div style={{display: 'flex', justifyContent: 'center', gap: 18, marginTop: 46}}>{['🥮', '🍪', '🍰', '🥠'].map((x, i) => <div key={x} style={{fontSize: 55, background: i % 2 ? C.paleBlue : C.white, border: `3px solid ${C.ink}`, borderRadius: 16, padding: '14px 10px', boxShadow: `4px 5px 0 ${i % 2 ? C.blue : C.yellow}`}}>{x}</div>)}</div><div style={{marginTop: 32, fontSize: 32, color: C.gray, fontWeight: 850}}>代表这家店的整体水准</div></Panel></div></Content></Frame>;

  if (kind === 7) return <Frame page={page} kicker="A股代表性指数" title={<>沪深300，<Mark color={C.yellow}>就是一只指数礼盒</Mark></>} subtitle="挑出300家规模大、流动性好的公司，打包成一个组合。" accent={C.blue} titleSize={88}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 35, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 500, height: 370, textAlign: 'center'}}><div style={{fontSize: 91, color: C.blue, fontWeight: 950}}>300</div><div style={{fontSize: 37, fontWeight: 950}}>家代表性公司</div><div style={{marginTop: 22, fontSize: 29, color: C.gray, fontWeight: 850}}>大盘核心 · 流动性好</div></Panel><Arrow color={C.yellow} size={94}>→</Arrow><Panel bg={C.white} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 760, height: 370, padding: '25px 45px'}}><div style={{fontSize: 38, fontWeight: 950, color: C.blue}}>沪深300 · 指数礼盒</div><div style={{display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginTop: 36}}>{['宁德时代', '中际旭创', '贵州茅台', '金融银行', '制造龙头', '消费品牌'].map((x, i) => <div key={x} style={{padding: '19px 8px', background: i % 2 ? C.paleYellow : C.paleBlue, border: `2px solid ${C.ink}`, borderRadius: 14, textAlign: 'center', fontSize: 29, fontWeight: 900}}>{x}</div>)}</div></Panel></div></Content></Frame>;

  if (kind === 8) return <Frame page={page} kicker="指数不是平均分配" title={<>权重，决定谁的影响<Mark color={C.yellow}>更大</Mark></>} subtitle="放得多的点心，更能改变整个礼盒的味道。" accent={C.yellow} titleSize={90}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 58, ...inView(18)}}><Panel bg={C.white} shadow={`11px 13px 0 ${C.blue}`} style={{width: 580, height: 380}}><div style={{fontSize: 39, fontWeight: 950}}>指数里的配方</div>{[['大权重', 78, C.blue], ['中权重', 53, C.yellow], ['小权重', 30, C.pink]].map(([label, width, color], i) => <div key={String(label)} style={{marginTop: 31, display: 'flex', alignItems: 'center', gap: 18}}><div style={{width: 115, fontSize: 27, fontWeight: 900}}>{label}</div><div style={{height: 34, width: `${Number(width)}%`, background: String(color), border: `3px solid ${C.ink}`, borderRadius: 10, scale: `${interpolate(frame, [28 + i * 25, 60 + i * 25], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})} 1`, transformOrigin: 'left'}} /></div>)}</Panel><Arrow color={C.yellow} size={92}>→</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 610, height: 380, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 68, color: C.blue, fontWeight: 950}}>权重</div><div style={{height: 4, background: C.blue, margin: '24px 70px'}} /><div style={{fontSize: 37, fontWeight: 950}}>每只个股的配比</div><div style={{marginTop: 18, fontSize: 30, color: C.gray, fontWeight: 850}}>影响力不同，涨跌贡献也不同</div></Panel></div></Content></Frame>;

  if (kind === 9) return <Frame page={page} kicker="ETF 的第一层精髓" title={<>ETF 做的事：<Mark color={C.yellow}>照着指数配方买</Mark></>} subtitle="指数里有哪300家公司，ETF就近似买哪300家。" accent={C.blue} titleSize={90}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 22, ...inView(18)}}><Step number="01" title="指数配方" desc="公司名单 + 权重比例" color={C.blue} bg={C.paleBlue} style={{width: 405}} /><Arrow color={C.yellow} /><Step number="02" title="ETF 组合" desc="按配方买入一篮子股票" color={C.yellow} bg={C.paleYellow} style={{width: 405}} /><Arrow color={C.yellow} /><Step number="03" title="你来持有" desc="一份ETF，近似跟上指数" color={C.blue} bg={C.white} style={{width: 405}} /></div><div style={{marginTop: 64, textAlign: 'center', ...inView(130)}}><Pill bg={C.yellow} style={{fontSize: 41}}>指数不能直接买，ETF 是买卖指数的工具</Pill></div></Content></Frame>;

  if (kind === 10) return <Frame page={page} kicker="ETF 的第二层精髓" title={<>指数涨它涨，<Mark color={C.yellow}>指数跌它跌</Mark></>} subtitle="它不追求超越指数，而是追求跟上大势。" accent={C.yellow} titleSize={95}><Content><Panel bg={C.white} shadow={`12px 14px 0 ${C.blue}`} style={{height: 390, padding: '30px 55px', ...inView(18)}}><div style={{display: 'flex', justifyContent: 'space-between', fontSize: 32, fontWeight: 950, color: C.gray}}><span>走势对照</span><span style={{color: C.blue}}>跟上，而不是猜中</span></div><LineChart frame={frame} matching color={C.blue} /><div style={{display: 'flex', justifyContent: 'center', gap: 44, marginTop: 12, fontSize: 31, fontWeight: 950}}><span style={{color: C.blue}}>● 指数</span><span style={{color: C.yellow}}>● ETF</span></div></Panel><div style={{marginTop: 54, textAlign: 'center', ...inView(135)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 43}}>这，就是ETF指数基金的精髓</Pill></div></Content></Frame>;

  if (kind === 11) return <Frame page={page} kicker="第二点 · ETF 是交易型" title={<>ETF 和股票一样，<Mark color={C.yellow}>可以场内交易</Mark></>} subtitle="场内，就是官方证券交易所：上交所、深交所、北交所。" accent={C.blue} titleSize={89}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 28, ...inView(18)}}>{[['上交所', 'SH', C.paleBlue, C.blue], ['深交所', 'SZ', C.paleYellow, C.yellow], ['北交所', 'BJ', C.pink, C.blue]].map(([name, code, bg, color], i) => <Panel key={String(name)} bg={String(bg)} shadow={`10px 12px 0 ${String(color)}`} style={{width: 400, height: 310, textAlign: 'center', opacity: fade(frame, i * 30, 16), translate: `0px ${rise(frame, i * 30)}px`}}><div style={{fontSize: 68, color: String(color), fontWeight: 950}}>{code}</div><div style={{height: 3, background: String(color), margin: '22px 38px'}} /><div style={{fontSize: 43, fontWeight: 950}}>{name}</div><div style={{marginTop: 14, fontSize: 29, color: C.gray, fontWeight: 850}}>官方证券交易所</div></Panel>)}</div><div style={{marginTop: 55, textAlign: 'center', ...inView(125)}}><Pill bg={C.yellow} style={{fontSize: 42}}>交易时间内，价格实时变动</Pill></div></Content></Frame>;

  if (kind === 12) return <Frame page={page} kicker="场内交易 · 动手步骤" title={<>打开软件，输入六位数<Mark color={C.yellow}>ETF代码</Mark></>} subtitle="看实时价格，随时买进卖出。" accent={C.yellow} titleSize={91}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 24, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 330, height: 360, textAlign: 'center', padding: 28}}><div style={{fontSize: 29, fontWeight: 950, textAlign: 'left'}}>证券软件</div><div style={{marginTop: 34, padding: '22px 18px', background: C.white, border: `3px solid ${C.ink}`, borderRadius: 12, fontSize: 41, letterSpacing: 4, fontWeight: 950}}>159300</div><div style={{marginTop: 25, fontSize: 30, color: C.gray, fontWeight: 850}}>沪深300ETF</div></Panel><Arrow color={C.yellow} size={86}>→</Arrow><Panel bg={C.white} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 470, height: 360, textAlign: 'center', padding: 30}}><div style={{fontSize: 33, color: C.gray, fontWeight: 900}}>实时价格</div><div style={{fontSize: 84, color: C.blue, fontWeight: 950, margin: '32px 0 18px'}}>4.126</div><div style={{fontSize: 35, color: C.blue, fontWeight: 950}}>+1.24%</div></Panel><Arrow color={C.yellow} size={86}>→</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 360, height: 360, textAlign: 'center', paddingTop: 90}}><div style={{fontSize: 55, fontWeight: 950}}>买 / 卖</div><div style={{marginTop: 18, fontSize: 30, color: C.gray, fontWeight: 850}}>像股票一样成交</div></Panel></div></Content></Frame>;

  if (kind === 13) return <Frame page={page} kicker="交易单位 · 别搞错" title={<>ETF 一手等于<Mark color={C.yellow}>100份</Mark></>} subtitle="不是买一份就算一笔，场内成交单位按手来算。" accent={C.blue} titleSize={100}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 70, ...inView(18)}}><div style={{fontSize: 190, lineHeight: 1, color: C.blue, fontWeight: 950}}>100</div><div style={{fontSize: 92, color: C.yellow, fontWeight: 950}}>份</div><Arrow color={C.yellow} size={110}>＝</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 420, height: 270, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 74, fontWeight: 950}}>1 手</div><div style={{marginTop: 15, fontSize: 32, color: C.gray, fontWeight: 850}}>最低成交单位</div></Panel></div><div style={{marginTop: 72, textAlign: 'center', ...inView(125)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 42}}>输入代码 → 看价格 → 按手买卖</Pill></div></Content></Frame>;

  if (kind === 14) return <Frame page={page} kicker="没有股票账户 · 你买到的是什么" title={<>后面跟着“联接”，<Mark color={C.yellow}>就是场外基金</Mark></>} subtitle="ETF 在场内，ETF联接基金在场外。" accent={C.yellow} titleSize={88}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 30, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 535, height: 340, textAlign: 'center'}}><div style={{fontSize: 61, color: C.blue, fontWeight: 950}}>ETF</div><div style={{marginTop: 22, fontSize: 42, fontWeight: 950}}>场内品种</div><div style={{marginTop: 23, fontSize: 31, color: C.gray, fontWeight: 850}}>券商账户 · 实时交易</div></Panel><Arrow color={C.yellow} size={100}>⇄</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 650, height: 340, textAlign: 'center'}}><div style={{fontSize: 61, color: C.blue, fontWeight: 950}}>ETF 联接</div><div style={{marginTop: 22, fontSize: 42, fontWeight: 950}}>场外品种</div><div style={{marginTop: 23, fontSize: 31, color: C.gray, fontWeight: 850}}>支付宝 / 基金APP · 一天一个价</div></Panel></div><div style={{marginTop: 58, textAlign: 'center', ...inView(120)}}><Pill bg={C.yellow} style={{fontSize: 42}}>没有股票账户，也能间接持有ETF</Pill></div></Content></Frame>;

  if (kind === 15) return <Frame page={page} kicker="ETF 联接 · 运作方式" title={<>基金公司帮你投向目标ETF，<Mark color={C.yellow}>比例不低于90%</Mark></>} subtitle="所以持有联接基金，能取得和ETF比较相似的收益率。" accent={C.blue} titleSize={85}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 30, ...inView(18)}}><Panel bg={C.white} shadow={`11px 13px 0 ${C.blue}`} style={{width: 390, height: 300, textAlign: 'center', paddingTop: 82}}><div style={{fontSize: 49, fontWeight: 950}}>你的钱</div></Panel><Arrow color={C.yellow} size={100}>→</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 470, height: 300, textAlign: 'center', paddingTop: 55}}><div style={{fontSize: 94, color: C.blue, fontWeight: 950}}>≥ 90%</div><div style={{marginTop: 13, fontSize: 33, fontWeight: 950}}>投向目标ETF</div></Panel><Arrow color={C.yellow} size={100}>→</Arrow><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 390, height: 300, textAlign: 'center', paddingTop: 82}}><div style={{fontSize: 47, color: C.blue, fontWeight: 950}}>近似跟上</div></Panel></div><div style={{marginTop: 64, textAlign: 'center', ...inView(125)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 41}}>联接基金 = 间接持有ETF</Pill></div></Content></Frame>;

  if (kind === 16) return <Frame page={page} kicker="场内 vs 场外 · 价格机制" title={<>最大的区别：<Mark color={C.yellow}>价格是不是实时变</Mark></>} subtitle="一个盯盘内价格，一个等交易日净值。" accent={C.yellow} titleSize={87}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 30, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 600, height: 370, textAlign: 'center'}}><div style={{fontSize: 49, color: C.blue, fontWeight: 950}}>ETF · 场内</div><div style={{fontSize: 82, fontWeight: 950, margin: '38px 0 20px'}}>实时变动</div><div style={{fontSize: 32, color: C.gray, fontWeight: 850}}>交易时间内随时买卖</div></Panel><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 600, height: 370, textAlign: 'center'}}><div style={{fontSize: 49, color: C.blue, fontWeight: 950}}>ETF联接 · 场外</div><div style={{fontSize: 82, fontWeight: 950, margin: '38px 0 20px'}}>一天一个价</div><div style={{fontSize: 32, color: C.gray, fontWeight: 850}}>下午三点前按收盘净值成交</div></Panel></div><div style={{marginTop: 58, textAlign: 'center', ...inView(125)}}><Pill bg={C.yellow} style={{fontSize: 39}}>第二个交易日，账户里看到盈亏</Pill></div></Content></Frame>;

  if (kind === 17) return <Frame page={page} kicker="怎么选 · 看你的需求" title={<>场内和场外，<Mark color={C.yellow}>各有各的好处</Mark></>} subtitle="能选场内就选场内，因为更便宜、更自由；想省心就看场外。" accent={C.blue} titleSize={90}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 32, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 585, height: 365, textAlign: 'center'}}><div style={{fontSize: 52, color: C.blue, fontWeight: 950}}>ETF · 场内</div><div style={{display: 'flex', justifyContent: 'center', gap: 18, marginTop: 53}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 38}}>更便宜</Pill><Pill bg={C.yellow} style={{fontSize: 38}}>更自由</Pill></div><div style={{marginTop: 28, fontSize: 31, color: C.gray, fontWeight: 850}}>适合有经验、能盯盘的人</div></Panel><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 585, height: 365, textAlign: 'center'}}><div style={{fontSize: 52, color: C.blue, fontWeight: 950}}>ETF联接 · 场外</div><div style={{display: 'flex', justifyContent: 'center', gap: 18, marginTop: 53}}><Pill bg={C.yellow} style={{fontSize: 38}}>更省心</Pill><Pill bg={C.blue} color={C.cream} style={{fontSize: 38}}>不用账户</Pill></div><div style={{marginTop: 28, fontSize: 31, color: C.gray, fontWeight: 850}}>适合想自动定投的人</div></Panel></div></Content></Frame>;

  if (kind === 18) return <Frame page={page} kicker="手续费 · 很多人忽略的成本" title={<>买1000块，为什么收5块？<br /><Mark color={C.yellow}>因为有最低收费</Mark></>} subtitle="做网格天天触发，手续费会慢慢变成一大笔。" accent={C.yellow} titleSize={82}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 26, ...inView(18)}}><Panel bg={C.white} shadow={`10px 12px 0 ${C.blue}`} style={{width: 350, height: 305, textAlign: 'center', paddingTop: 45}}><div style={{fontSize: 36, fontWeight: 950}}>买入金额</div><div style={{fontSize: 83, color: C.blue, fontWeight: 950, marginTop: 30}}>¥1000</div></Panel><Arrow color={C.yellow} size={92}>→</Arrow><Panel bg={C.paleYellow} shadow={`10px 12px 0 ${C.yellow}`} style={{width: 400, height: 305, textAlign: 'center', paddingTop: 45}}><div style={{fontSize: 36, fontWeight: 950}}>理论手续费</div><div style={{fontSize: 83, color: C.blue, fontWeight: 950, marginTop: 30}}>¥0.2</div></Panel><Arrow color={C.yellow} size={92}>→</Arrow><Panel bg={C.pink} shadow={`10px 12px 0 ${C.blue}`} style={{width: 350, height: 305, textAlign: 'center', paddingTop: 45}}><div style={{fontSize: 36, fontWeight: 950}}>实际收取</div><div style={{fontSize: 83, color: C.ink, fontWeight: 950, marginTop: 30}}>¥5</div></Panel></div><div style={{marginTop: 57, textAlign: 'center', ...inView(130)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 43}}>免5 = 去掉每笔最低5块的限制</Pill></div></Content></Frame>;

  if (kind === 19) return <Frame page={page} kicker="手续费 · 找到合适费率" title={<>免5之后，<Mark color={C.blue}>费率也要谈</Mark></>} subtitle="万0.5左右，频繁买卖时才不会被成本拖住。" accent={C.blue} titleSize={92}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 28, ...inView(18)}}><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 470, height: 315, textAlign: 'center', paddingTop: 44}}><div style={{fontSize: 38, fontWeight: 950}}>普通账户</div><div style={{fontSize: 78, color: C.blue, fontWeight: 950, margin: '34px 0 15px'}}>万2.3+</div><div style={{fontSize: 29, color: C.gray, fontWeight: 850}}>还有最低5块</div></Panel><Arrow color={C.yellow} size={94}>→</Arrow><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 560, height: 315, textAlign: 'center', paddingTop: 44}}><div style={{fontSize: 38, fontWeight: 950}}>免5账户</div><div style={{fontSize: 78, color: C.blue, fontWeight: 950, margin: '34px 0 15px'}}>万0.5</div><div style={{fontSize: 29, color: C.gray, fontWeight: 850}}>买1万只收5毛</div></Panel></div><div style={{marginTop: 55, textAlign: 'center', ...inView(125)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 38}}>不同营业部规则不同，最好有人引荐</Pill></div></Content></Frame>;

  if (kind === 20) return <Frame page={page} kicker="场内交易 · 另一个难点" title={<>价格波动剧烈，<Mark color={C.yellow}>需要盯盘</Mark></>} subtitle="挂低了买不进，挂高了卖不出，稍微犹豫价格就变了。" accent={C.blue} titleSize={91}><Content><Panel bg={C.white} shadow={`12px 14px 0 ${C.blue}`} style={{height: 375, padding: '28px 52px', ...inView(18)}}><div style={{display: 'flex', justifyContent: 'space-between', fontSize: 34, fontWeight: 950}}><span>实时盘口</span><span style={{color: C.blue}}>4.126 <span style={{color: C.yellow}}>+1.24%</span></span></div><LineChart frame={frame} color={C.blue} /><div style={{display: 'flex', justifyContent: 'center', gap: 30, marginTop: 15}}><Pill bg={C.paleBlue} style={{fontSize: 35}}>挂低 → 买不进</Pill><Pill bg={C.paleYellow} style={{fontSize: 35}}>挂高 → 卖不出</Pill></div></Panel><div style={{marginTop: 53, textAlign: 'center', ...inView(130)}}><Pill bg={C.yellow} style={{fontSize: 42}}>价格会影响操作，也会影响心态</Pill></div></Content></Frame>;

  if (kind === 21) return <Frame page={page} kicker="定投 · 场内与场外的差别" title={<>想自动定投？<Mark color={C.yellow}>场外更省心</Mark></>} subtitle="每周、每月自动扣款，还能设置均线定投；ETF则要自己盯盘操作。" accent={C.yellow} titleSize={91}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 30, ...inView(18)}}><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 585, height: 365, textAlign: 'center'}}><div style={{fontSize: 49, fontWeight: 950}}>ETF联接 · 场外</div><div style={{fontSize: 78, color: C.blue, fontWeight: 950, margin: '40px 0 22px'}}>自动扣款</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>每周 / 每月 / 智能定投</div></Panel><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 585, height: 365, textAlign: 'center'}}><div style={{fontSize: 49, fontWeight: 950}}>ETF · 场内</div><div style={{fontSize: 78, color: C.blue, fontWeight: 950, margin: '40px 0 22px'}}>自己盯盘</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>买卖时机需要自己执行</div></Panel></div><div style={{marginTop: 58, textAlign: 'center', ...inView(130)}}><Pill bg={C.blue} color={C.cream} style={{fontSize: 40}}>省心和自由，选你真正需要的</Pill></div></Content></Frame>;

  return <Frame page={page} kicker="ETF 入门 · 最后总结" title={<>场内还是场外？<br /><Mark color={C.yellow}>按你的需求来选</Mark></>} subtitle="能盯盘、想省费用 → 场内；想省心、不想开账户 → ETF联接。" accent={C.blue} titleSize={91}><Content style={{top: 468}}><div style={{display: 'flex', justifyContent: 'center', gap: 24, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 570, height: 300, textAlign: 'center', paddingTop: 46}}><div style={{fontSize: 45, color: C.blue, fontWeight: 950}}>场内 ETF</div><div style={{marginTop: 25, fontSize: 36, fontWeight: 950}}>有经验 · 能盯盘</div><Pill bg={C.yellow} style={{marginTop: 25, fontSize: 32}}>省费用 + 更自由</Pill></Panel><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 570, height: 300, textAlign: 'center', paddingTop: 46}}><div style={{fontSize: 45, color: C.blue, fontWeight: 950}}>ETF 联接</div><div style={{marginTop: 25, fontSize: 36, fontWeight: 950}}>想省心 · 无账户</div><Pill bg={C.blue} color={C.cream} style={{marginTop: 25, fontSize: 32}}>少操作 + 可定投</Pill></Panel></div><div style={{marginTop: 53, textAlign: 'center', ...inView(120)}}><Pill bg={C.yellow} style={{fontSize: 42}}>你现在做的是场内还是场外？评论区聊聊</Pill></div><div style={{marginTop: 28, textAlign: 'center', fontSize: 32, color: C.gray, fontWeight: 850, ...inView(175)}}>我是剑平，我们下期再见</div></Content></Frame>;
};

const SCENE_KINDS = Array.from({length: PAGE_COUNT}, (_, index) => index + 1);

export const ETFExplainerVideo: React.FC = () => <AbsoluteFill style={{background: C.cream}}>
  <Audio src={staticFile('etf-explainer.mp3')} />
  <Sequence from={0} durationInFrames={TOTAL_FRAMES} layout="none">
    {SCENE_START_FRAMES.map((start, index) => <Sequence key={start} from={start} durationInFrames={SCENE_FRAMES[index]} layout="none"><PageSfx /><SceneSfx kind={SCENE_KINDS[index]} /><SceneVisual kind={SCENE_KINDS[index]} page={index + 1} /></Sequence>)}
  </Sequence>
  <CaptionOverlay />
</AbsoluteFill>;
