import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {ETF_GRID_CAPTIONS} from './etfGridCaptions';

const C = {
  ink: '#151515',
  yellow: '#fdca17',
  blue: '#1e50a2',
  cream: '#fff2df',
  gray: '#626262',
  paleBlue: '#dce8fb',
  paleYellow: '#ffe38a',
  white: '#fffaf2',
};
const FONT = '"PingFang SC", "Noto Sans CJK SC", "Microsoft YaHei", Arial, sans-serif';
const FPS = 30;
const TOTAL_FRAMES = 11588;
const SCENE_STARTS = [0, 582, 966, 1824, 2310, 3114, 3423, 4497, 5535, 6264, 6812, 7277, 7951, 8183, 8723, 9024, 9767, 10422, 11157, 11315];
const SCENE_FRAMES = SCENE_STARTS.map((start, i) => i === SCENE_STARTS.length - 1 ? TOTAL_FRAMES - start : SCENE_STARTS[i + 1] - start);

const fade = (frame: number, delay = 0, duration = 18) => interpolate(frame, [delay, delay + duration], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.bezier(0.16, 1, 0.3, 1)});
const rise = (frame: number, delay = 0, distance = 30) => interpolate(frame, [delay, delay + 18], [distance, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.bezier(0.16, 1, 0.3, 1)});
const enter = (frame: number, delay = 0, distance = 30) => ({opacity: fade(frame, delay), translate: `0px ${rise(frame, delay, distance)}px`});

const Mark: React.FC<{children: React.ReactNode; color?: string}> = ({children, color = C.yellow}) => <span style={{position: 'relative', display: 'inline-block', zIndex: 0}}><span style={{position: 'absolute', left: -10, right: -10, bottom: 7, height: 24, borderRadius: 5, background: color, zIndex: -1}} />{children}</span>;
const Panel: React.FC<{children: React.ReactNode; bg?: string; shadow?: string; style?: React.CSSProperties}> = ({children, bg = C.white, shadow = `11px 13px 0 ${C.blue}`, style}) => <div style={{boxSizing: 'border-box', padding: '32px 38px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 28, boxShadow: shadow, ...style}}>{children}</div>;
const Pill: React.FC<{children: React.ReactNode; bg?: string; style?: React.CSSProperties}> = ({children, bg = C.yellow, style}) => <div style={{display: 'inline-block', padding: '13px 27px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 999, fontSize: 31, fontWeight: 950, lineHeight: 1.05, ...style}}>{children}</div>;
const Arrow: React.FC<{children?: React.ReactNode; color?: string; size?: number}> = ({children = '→', color = C.blue, size = 76}) => <div style={{fontSize: size, lineHeight: 1, fontWeight: 950, color}}>{children}</div>;

const Frame: React.FC<{page: number; kicker: string; title: React.ReactNode; subtitle?: React.ReactNode; accent?: string; titleSize?: number; children: React.ReactNode}> = ({page, kicker, title, subtitle, accent = C.blue, titleSize = 88, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background: C.cream, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', inset: 0, opacity: 0.6, backgroundImage: 'linear-gradient(rgba(21,21,21,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(21,21,21,0.08) 1px, transparent 1px)', backgroundSize: '48px 48px'}} />
    <div style={{position: 'absolute', left: -100, top: 340, width: 210, height: 210, border: `20px solid ${accent}`, borderRadius: 48, rotate: '-12deg', opacity: 0.52}} />
    <div style={{position: 'absolute', right: -160, bottom: -220, width: 520, height: 520, borderRadius: '50%', background: accent, opacity: 0.72}} />
    <div style={{position: 'absolute', left: 126, top: 78, display: 'flex', alignItems: 'center', gap: 18, color: accent, fontSize: 31, fontWeight: 950, letterSpacing: 4, opacity: fade(frame)}}><span style={{display: 'inline-block', width: 54, height: 14, background: accent}} />{kicker}</div>
    <div style={{position: 'absolute', right: 126, top: 76, color: C.gray, fontSize: 27, fontWeight: 900, letterSpacing: 4, opacity: fade(frame)}}>{String(page).padStart(2, '0')} / 20</div>
    <div style={{position: 'absolute', left: 126, right: 126, top: 158, ...enter(frame, 6)}}>
      <div style={{fontSize: titleSize, lineHeight: 1.08, fontWeight: 950, letterSpacing: -4}}>{title}</div>
      {subtitle && <div style={{marginTop: 22, fontSize: 44, lineHeight: 1.25, color: C.gray, fontWeight: 850}}>{subtitle}</div>}
    </div>
    {children}
  </AbsoluteFill>;
};

const Content: React.FC<{children: React.ReactNode; style?: React.CSSProperties}> = ({children, style}) => <div style={{position: 'absolute', left: 126, right: 126, top: 405, bottom: 38, ...style}}>{children}</div>;
const GridLine: React.FC<{frame: number; y: number; color?: string}> = ({frame, y, color = C.blue}) => <div style={{position: 'absolute', left: 0, right: 0, top: y, height: 4, background: color, transformOrigin: 'left', scale: `${interpolate(frame, [12, 38], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})} 1`}} />;

const PageSfx = () => <Audio src={staticFile('sfx/whoosh.mp3')} volume={0.36} />;
const MOTION_TIMES: Record<number, number[]> = {1: [20, 110], 2: [18, 90, 145], 3: [18, 95], 4: [20, 92], 5: [18, 88, 145], 6: [18, 75, 132, 190], 7: [18, 92, 166], 8: [18, 78, 140], 9: [18, 72, 132, 190], 10: [18, 90], 11: [18, 80, 150], 12: [18, 92], 13: [18, 88, 150], 14: [18, 100, 190], 15: [18, 100], 16: [18, 90], 17: [18, 88, 150], 18: [18, 92, 166], 19: [18, 100], 20: [18, 110]};
const MotionSfx: React.FC<{at: number}> = ({at}) => <Sequence from={at} durationInFrames={28}><Audio src={staticFile('sfx/pop.mp3')} volume={0.195} /></Sequence>;
const SceneSfx: React.FC<{kind: number}> = ({kind}) => <>{(MOTION_TIMES[kind] ?? [20]).map((at) => <MotionSfx key={at} at={at} />)}</>;

const CaptionOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const timeMs = frame / FPS * 1000;
  const caption = ETF_GRID_CAPTIONS.find((item) => item.startMs <= timeMs && item.endMs > timeMs);
  if (!caption) return null;
  return <div style={{position: 'absolute', left: 170, right: 170, bottom: 28, display: 'flex', justifyContent: 'center', pointerEvents: 'none'}}><div style={{maxWidth: 1560, padding: '12px 28px 14px', borderRadius: 16, background: 'rgba(21,21,21,0.9)', color: C.cream, border: `2px solid ${C.ink}`, boxShadow: `6px 7px 0 ${C.yellow}`, fontSize: 37, lineHeight: 1.3, fontWeight: 850, textAlign: 'center', letterSpacing: 1}}>{caption.text}</div></div>;
};

const MiniCard: React.FC<{value: string; label: string; color?: string; bg?: string}> = ({value, label, color = C.blue, bg = C.white}) => <Panel bg={bg} shadow={`9px 11px 0 ${color}`} style={{height: 230, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 61, fontWeight: 950, color}}>{value}</div><div style={{marginTop: 16, fontSize: 31, color: C.gray, fontWeight: 850}}>{label}</div></Panel>;

const Wave: React.FC<{frame: number; color?: string; mode?: 'wave' | 'rise' | 'fall'}> = ({frame, color = C.blue, mode = 'wave'}) => {
  const points = mode === 'rise' ? '0,235 110,215 220,188 330,158 440,130 550,92 660,58 770,32 880,10' : mode === 'fall' ? '0,18 110,42 220,65 330,100 440,124 550,155 660,182 770,210 880,238' : '0,135 70,78 140,188 210,58 280,155 350,94 420,206 490,70 560,160 630,82 700,182 770,64 880,133';
  return <svg width="100%" height="270" viewBox="0 0 880 270" preserveAspectRatio="none" style={{overflow: 'visible'}}><path d="M 0 240 H 880" stroke={C.ink} strokeWidth="4" opacity="0.4" /><path d="M 0 135 H 880" stroke={C.ink} strokeWidth="2" strokeDasharray="8 12" opacity="0.18" /><polyline points={points} fill="none" stroke={color} strokeWidth="13" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="1400 1400" strokeDashoffset={interpolate(frame, [12, 55], [1400, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})} /><circle cx="880" cy={mode === 'rise' ? 10 : mode === 'fall' ? 238 : 133} r="14" fill={C.yellow} stroke={C.ink} strokeWidth="4" /></svg>;
};

const SceneVisual: React.FC<{kind: number; page: number}> = ({kind, page}) => {
  const frame = useCurrentFrame();
  const inView = (delay = 18, distance = 32) => enter(frame, delay, distance);
  if (kind === 1) return <Frame page={page} kicker="ETF网格交易 · 实操指南" title={<>ETF网格，<br /><Mark color={C.yellow}>到底还能不能做？</Mark></>} subtitle="今天不讲虚的，照着规则做就行。" accent={C.blue} titleSize={101}><Content style={{top: 465}}><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 40, ...inView(20)}}><Panel bg={C.paleYellow} shadow={`12px 14px 0 ${C.yellow}`} style={{width: 780, height: 292, textAlign: 'center'}}><Pill bg={C.yellow}>今天回答 3 个问题</Pill><div style={{marginTop: 32, fontSize: 51, fontWeight: 950}}>能不能做？适合谁？</div><div style={{marginTop: 15, fontSize: 37, color: C.gray, fontWeight: 850}}>4% 怎么设 · 备用金留多少</div></Panel><Arrow /><Panel bg={C.paleBlue} shadow={`12px 14px 0 ${C.blue}`} style={{width: 500, height: 292, textAlign: 'center'}}><div style={{fontSize: 78, fontWeight: 950}}>规则</div><div style={{fontSize: 39, fontWeight: 900, color: C.blue}}>比预测更重要</div></Panel></div><div style={{marginTop: 55, textAlign: 'center', ...inView(110)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 40}}>哈喽，我是剑平</Pill></div></Content></Frame>;

  if (kind === 2) return <Frame page={page} kicker="先搞明白 · 网格赚什么" title={<>网格的本质，<Mark color={C.yellow}>就八个字</Mark></>} subtitle="跌了买点，涨了卖点。" accent={C.yellow} titleSize={96}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 34, ...inView(18)}}><MiniCard value="跌" label="买一点" color={C.blue} bg={C.paleBlue} /><Arrow color={C.yellow}>→</Arrow><Panel bg={C.paleYellow} shadow={`10px 12px 0 ${C.yellow}`} style={{width: 470, height: 250, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 57, fontWeight: 950}}>区间</div><div style={{fontSize: 32, color: C.gray, fontWeight: 850}}>来回折腾</div></Panel><Arrow color={C.yellow}>→</Arrow><MiniCard value="涨" label="卖一点" color={C.blue} bg={C.paleBlue} /></div><div style={{marginTop: 65, ...inView(100)}}><Panel bg={C.white} shadow={`9px 11px 0 ${C.blue}`} style={{height: 190, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 28}}><div style={{fontSize: 48, fontWeight: 950}}>不猜方向</div><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 48, fontWeight: 950, color: C.blue}}>只执行价差</div></Panel></div></Content></Frame>;

  if (kind === 3) return <Frame page={page} kicker="为什么优先用ETF" title={<>网格最怕的，<Mark color={C.yellow}>不是波动</Mark></>} subtitle="是标的自己废了。股票爆雷，本金可能直接归零。" accent={C.blue} titleSize={84}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 35, ...inView(18)}}><Panel bg={C.white} shadow={`11px 13px 0 ${C.blue}`} style={{width: 560, height: 300, textAlign: 'center'}}><div style={{fontSize: 62, fontWeight: 950}}>单只股票</div><div style={{marginTop: 28, fontSize: 64, fontWeight: 950, color: C.blue}}>爆雷</div><div style={{marginTop: 12, fontSize: 32, color: C.gray, fontWeight: 850}}>本金可能归零</div></Panel><Arrow color={C.yellow}>→</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 690, height: 300, textAlign: 'center'}}><div style={{fontSize: 62, fontWeight: 950}}>ETF 一篮子资产</div><div style={{marginTop: 28, fontSize: 64, fontWeight: 950, color: C.blue}}>个别出问题</div><div style={{marginTop: 12, fontSize: 32, color: C.gray, fontWeight: 850}}>伤不到整体</div></Panel></div><div style={{marginTop: 55, display: 'flex', justifyContent: 'center', gap: 24, ...inView(105)}}>{['门槛低', '格子多', '免印花税'].map((x, i) => <Pill key={x} bg={i === 1 ? C.blue : C.yellow} style={i === 1 ? {color: C.cream} : {}}>{x}</Pill>)}</div></Content></Frame>;

  if (kind === 4) return <Frame page={page} kicker="网格只吃一种行情" title={<>最舒服的环境：<Mark color={C.yellow}>震荡行情</Mark></>} subtitle="涨不上天，跌不穿地，价格在区间里来回。" accent={C.blue} titleSize={92}><Content><Panel bg={C.white} shadow={`12px 14px 0 ${C.blue}`} style={{height: 350, padding: '38px 55px', ...inView(18)}}><div style={{display: 'flex', justifyContent: 'space-between', marginBottom: 12, fontSize: 32, fontWeight: 950, color: C.gray}}><span>上沿</span><span style={{color: C.blue}}>来回赚差价</span><span>下沿</span></div><Wave frame={frame} color={C.blue} mode="wave" /></Panel><div style={{marginTop: 58, display: 'flex', justifyContent: 'center', gap: 22, ...inView(100)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 42}}>跌了买</Pill><Arrow color={C.yellow}>→</Arrow><Pill bg={C.yellow} style={{fontSize: 42}}>涨了卖</Pill></div></Content></Frame>;

  if (kind === 5) return <Frame page={page} kicker="网格的坟场" title={<>两种行情，<Mark color={C.yellow}>千万别硬做</Mark></>} subtitle="一路猛涨，或者一路猛跌。" accent={C.yellow} titleSize={94}><Content><div style={{display: 'flex', gap: 30, justifyContent: 'center', ...inView(18)}}><div style={{width: 690}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{height: 300, padding: '28px 44px'}}><div style={{fontSize: 43, fontWeight: 950}}>单边上涨</div><Wave frame={frame} color={C.blue} mode="rise" /></Panel><div style={{marginTop: 22, textAlign: 'center', fontSize: 42, lineHeight: 1.2, fontWeight: 950, color: C.blue}}>越卖越少，<br />最后空仓干看</div></div><div style={{width: 690}}><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{height: 300, padding: '28px 44px'}}><div style={{fontSize: 43, fontWeight: 950}}>单边下跌</div><Wave frame={frame} color={C.yellow} mode="fall" /></Panel><div style={{marginTop: 22, textAlign: 'center', fontSize: 42, lineHeight: 1.2, fontWeight: 950, color: C.ink}}>越买越多，<br />子弹很快打完</div></div></div><div style={{marginTop: 40, textAlign: 'center', ...inView(115)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 40}}>震荡才是主场 · 单边就是风险</Pill></div></Content></Frame>;

  if (kind === 6) { const etfs = [['沪深300', '大盘核心 · 相对稳', C.blue, C.paleBlue], ['中证500', '弹性更大 · 差价足', C.yellow, C.paleYellow], ['创业板50', '波动猛 · 要控仓', C.blue, C.paleBlue], ['科创50', '高波动 · 要有心态', C.yellow, C.paleYellow]]; return <Frame page={page} kicker="第三 · 哪些ETF能用" title={<>先拿这四类<Mark color={C.yellow}>宽基练手</Mark></>} subtitle="够主流、够活跃、波动也够用。" accent={C.blue} titleSize={92}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 22, ...inView(18)}}>{etfs.map(([name, desc, color, bg], i) => <Panel key={String(name)} bg={String(bg)} shadow={`9px 11px 0 ${color}`} style={{height: 340, textAlign: 'center', padding: '28px 18px', opacity: fade(frame, i * 28, 14), translate: `0px ${rise(frame, i * 28)}px`}}><div style={{fontSize: 42, fontWeight: 950, color: i % 2 ? C.ink : C.blue}}>{name}</div><div style={{height: 3, background: String(color), margin: '28px 10px'}} /><div style={{fontSize: 29, color: C.gray, lineHeight: 1.35, fontWeight: 850}}>{desc}</div><div style={{marginTop: 35, fontSize: 46, fontWeight: 950, color: String(color)}}>{i < 2 ? '稳' : '猛'}</div></Panel>)}</div><div style={{marginTop: 54, textAlign: 'center', ...inView(155)}}><Pill bg={C.yellow} style={{fontSize: 39}}>新手别一上来碰情绪化主题ETF</Pill></div></Content></Frame>; }

  if (kind === 7) { const rows = [['沪深300', '大盘核心', '相对稳', C.blue, C.paleBlue], ['中证500', '弹性更大', '差价足', C.yellow, C.paleYellow], ['创业板50', '波动最猛', '要控仓', C.blue, C.paleBlue], ['科创50', '高波动', '要心态', C.yellow, C.paleYellow]]; return <Frame page={page} kicker="为什么是这四类" title={<>挑网格标的，<Mark color={C.blue}>看三个共同点</Mark></>} subtitle="把四个名字和三个标准放在一起，才知道怎么选。" accent={C.yellow} titleSize={88}><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 18, ...inView(18)}}>{rows.map(([name, a, b, color, bg], i) => <Panel key={String(name)} bg={String(bg)} shadow={`9px 11px 0 ${color}`} style={{minWidth: 0, height: 300, padding: '25px 10px', textAlign: 'center', opacity: fade(frame, i * 26, 14), translate: `0px ${rise(frame, i * 26)}px`}}><div style={{fontSize: 34, fontWeight: 950, whiteSpace: 'nowrap'}}>{name}</div><div style={{height: 3, background: String(color), margin: '23px 8px'}} /><div style={{fontSize: 29, fontWeight: 950, color: C.blue, whiteSpace: 'nowrap'}}>{a}</div><div style={{marginTop: 14, fontSize: 27, color: C.gray, fontWeight: 850, whiteSpace: 'nowrap'}}>{b}</div></Panel>)}</div><div style={{marginTop: 42, display: 'flex', justifyContent: 'center', gap: 24, ...inView(110)}}>{[['够主流', C.yellow], ['够活跃', C.blue], ['波动够用', C.yellow]].map(([x, color], i) => <Pill key={String(x)} bg={String(color)} style={i === 1 ? {color: C.cream, fontSize: 37} : {fontSize: 37}}>{x}</Pill>)}</div><div style={{marginTop: 32, textAlign: 'center', ...inView(165)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 34}}>新手先拿宽基练手</Pill></div></Content></Frame>; }

  if (kind === 8) return <Frame page={page} kicker="第四 · 参数怎么定" title={<>不知道比例？<Mark color={C.yellow}>先用4%</Mark></>} subtitle="相对基准价，跌4%买一笔，涨4%卖一笔。" accent={C.blue} titleSize={100}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'stretch', gap: 24, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 500, height: 330, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 42, fontWeight: 950, color: C.blue}}>价格下移</div><div style={{fontSize: 84, fontWeight: 950, margin: '20px 0'}}>−4%</div><Pill bg={C.blue} style={{color: C.cream, fontSize: 42}}>买一笔</Pill></Panel><Panel bg={C.white} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 400, height: 330, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 35, color: C.gray, fontWeight: 900}}>基准价</div><div style={{fontSize: 96, color: C.ink, fontWeight: 950, margin: '16px 0'}}>4.00</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>每格固定4%</div></Panel><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 500, height: 330, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 42, fontWeight: 950, color: C.blue}}>价格上移</div><div style={{fontSize: 84, fontWeight: 950, margin: '20px 0'}}>＋4%</div><Pill bg={C.yellow} style={{fontSize: 42}}>卖一笔</Pill></Panel></div><div style={{marginTop: 52, textAlign: 'center', ...inView(110)}}><Pill bg={C.yellow} style={{fontSize: 40}}>4% 不一定最优，但很适合作为起步</Pill></div></Content></Frame>;

  if (kind === 9) return <Frame page={page} kicker="4% 网格 · 价格示例" title={<>沪深300ETF，<Mark color={C.yellow}>怎么一步步动手？</Mark></>} subtitle="基准价4块，价格到了就执行。" accent={C.blue} titleSize={83}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 34, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`10px 12px 0 ${C.blue}`} style={{width: 625, height: 370, textAlign: 'center', padding: '26px 38px'}}><div style={{fontSize: 39, fontWeight: 950, color: C.blue}}>下跌 · 触发买入</div><div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-around', marginTop: 38}}><div><div style={{fontSize: 47, fontWeight: 950}}>4.00</div><div style={{fontSize: 30, color: C.gray, fontWeight: 850}}>基准价</div></div><Arrow color={C.blue} size={58}>↓</Arrow><div><div style={{fontSize: 47, fontWeight: 950}}>3.84</div><div style={{fontSize: 30, color: C.blue, fontWeight: 950}}>买一笔</div></div></div><div style={{marginTop: 26, fontSize: 36, color: C.blue, fontWeight: 950}}>再跌4% → 3.686 · 再买一笔</div></Panel><Panel bg={C.paleYellow} shadow={`10px 12px 0 ${C.yellow}`} style={{width: 625, height: 370, textAlign: 'center', padding: '26px 38px'}}><div style={{fontSize: 39, fontWeight: 950, color: C.blue}}>上涨 · 触发卖出</div><div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-around', marginTop: 38}}><div><div style={{fontSize: 47, fontWeight: 950}}>4.00</div><div style={{fontSize: 30, color: C.gray, fontWeight: 850}}>基准价</div></div><Arrow color={C.yellow} size={58}>↑</Arrow><div><div style={{fontSize: 47, fontWeight: 950}}>4.16</div><div style={{fontSize: 30, color: C.yellow, fontWeight: 950}}>卖一笔</div></div></div><div style={{marginTop: 26, fontSize: 36, color: C.yellow, fontWeight: 950}}>再涨4% → 4.326 · 再卖一笔</div></Panel></div><div style={{marginTop: 50, textAlign: 'center', ...inView(115)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 42}}>不预测行情，只把动作规则化</Pill></div></Content></Frame>;

  if (kind === 10) return <Frame page={page} kicker="第五 · 每格买多少" title={<>别让子弹<Mark color={C.yellow}>三五格就打光</Mark></>} subtitle="先看一个最容易犯的错误。" accent={C.yellow} titleSize={90}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 34, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 720, height: 360, textAlign: 'center', padding: '38px 50px'}}><div style={{fontSize: 43, fontWeight: 950}}>总资金 ¥1万</div><div style={{fontSize: 91, color: C.blue, fontWeight: 950, margin: '40px 0 22px'}}>¥3000 × 3</div><div style={{fontSize: 39, color: C.gray, fontWeight: 850}}>连续跌几格，就没钱了</div></Panel><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 74, color: C.yellow, fontWeight: 950}}>缴械</div></div><div style={{marginTop: 66, textAlign: 'center', ...inView(112)}}><Pill bg={C.yellow} style={{fontSize: 44}}>这种网格是假的，根本没有持续作战能力</Pill></div></Content></Frame>;

  if (kind === 16) return <Frame page={page} kicker="第五 · 正确拆法" title={<>准备投1万，<Mark color={C.blue}>拆成8到12格</Mark></>} subtitle="每次触发买800到1200左右，给连续下跌留下空间。" accent={C.blue} titleSize={88}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 18, ...inView(18)}}><div style={{display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 13, width: 930}}>{Array.from({length: 12}).map((_, i) => <div key={i} style={{height: 85, border: `3px solid ${C.ink}`, borderRadius: 12, background: i < 6 ? C.blue : C.yellow, color: i < 6 ? C.cream : C.ink, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28, fontWeight: 950, opacity: fade(frame, 18 + i * 8, 12), scale: interpolate(frame, [18 + i * 8, 30 + i * 8], [0.7, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}}>{i + 1}</div>)}</div></div><div style={{marginTop: 48, display: 'flex', justifyContent: 'center', gap: 24, ...inView(135)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 42}}>每格 ¥800—1200</Pill><Pill bg={C.yellow} style={{fontSize: 42}}>留足持续作战能力</Pill></div></Content></Frame>;

  if (kind === 17) return <Frame page={page} kicker="备用金 · 高波动要留厚" title={<>创业板50、科创50，<Mark color={C.yellow}>子弹要更多</Mark></>} subtitle="波动越猛，连续触发的可能性越高，备用金不能太薄。" accent={C.yellow} titleSize={82}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 30, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 590, height: 320, textAlign: 'center'}}><div style={{fontSize: 43, fontWeight: 950}}>普通宽基</div><div style={{height: 56, margin: '45px 30px 24px', background: C.blue, border: `3px solid ${C.ink}`, borderRadius: 12}} /><div style={{fontSize: 32, color: C.gray, fontWeight: 850}}>备用金正常留</div></Panel><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 590, height: 320, textAlign: 'center'}}><div style={{fontSize: 43, fontWeight: 950}}>高波动宽基</div><div style={{height: 56, margin: '45px 30px 24px', background: `linear-gradient(90deg, ${C.yellow} 0 72%, ${C.blue} 72%)`, border: `3px solid ${C.ink}`, borderRadius: 12}} /><div style={{fontSize: 32, color: C.gray, fontWeight: 850}}>备用金要留厚一点</div></Panel></div><div style={{marginTop: 62, textAlign: 'center', ...inView(115)}}><Pill bg={C.yellow} style={{fontSize: 42}}>先保证能连续作战，再追求效率</Pill></div></Content></Frame>;

  if (kind === 11) return <Frame page={page} kicker="第六 · 备用资金最重要" title={<>10万资金，<Mark color={C.yellow}>不要一开始满仓</Mark></>} subtitle="底仓负责持有，备用金负责应对连续触发。" accent={C.blue} titleSize={90}><Content><Panel bg={C.white} shadow={`12px 14px 0 ${C.blue}`} style={{height: 260, padding: '42px 52px', ...inView(18)}}><div style={{display: 'flex', justifyContent: 'space-between', fontSize: 37, fontWeight: 950}}><span>总资金 ¥10万</span><span style={{color: C.blue}}>先分成两部分</span></div><div style={{display: 'flex', height: 82, marginTop: 35, border: `3px solid ${C.ink}`, borderRadius: 14, overflow: 'hidden'}}><div style={{width: '58%', background: C.blue, color: C.cream, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 43, fontWeight: 950}}>底仓 ¥5—6万</div><div style={{width: '42%', background: C.yellow, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 39, fontWeight: 950}}>备用 ¥4—5万</div></div></Panel><div style={{marginTop: 55, display: 'flex', justifyContent: 'center', gap: 28, ...inView(100)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 40}}>高波动品种 → 备用金留厚一点</Pill></div></Content></Frame>;

  if (kind === 12) return <Frame page={page} kicker="备用金放哪儿" title={<>别让现金<Mark color={C.yellow}>傻趴着</Mark></>} subtitle="要有一点收益，也要能在需要时快速挪出来。" accent={C.yellow} titleSize={96}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 34, ...inView(18)}}><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 450, height: 285, textAlign: 'center'}}><div style={{fontSize: 49, fontWeight: 950}}>备用金</div><div style={{marginTop: 28, fontSize: 36, color: C.gray, fontWeight: 850}}>随时可用</div></Panel><Arrow color={C.yellow}>→</Arrow><div style={{display: 'flex', gap: 25}}><Panel bg={C.paleYellow} shadow={`9px 11px 0 ${C.yellow}`} style={{width: 360, height: 285, textAlign: 'center'}}><div style={{fontSize: 43, fontWeight: 950}}>短融ETF</div><div style={{marginTop: 32, fontSize: 32, color: C.gray, fontWeight: 850}}>小收益</div></Panel><Panel bg={C.paleBlue} shadow={`9px 11px 0 ${C.blue}`} style={{width: 360, height: 285, textAlign: 'center'}}><div style={{fontSize: 43, fontWeight: 950}}>国债逆回购</div><div style={{marginTop: 32, fontSize: 32, color: C.gray, fontWeight: 850}}>快挪出</div></Panel></div></div><div style={{marginTop: 60, textAlign: 'center', ...inView(115)}}><Pill bg={C.yellow} style={{fontSize: 42}}>别因为怕浪费，就把备用金全压进去</Pill></div></Content></Frame>;

  if (kind === 13) return <Frame page={page} kicker="开户前先分清" title={<>场内和场外，<Mark color={C.yellow}>不是一回事</Mark></>} subtitle="做网格，只能买场内ETF。" accent={C.blue} titleSize={94}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 34, ...inView(18)}}><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 650, height: 330}}><Pill bg={C.yellow}>场外</Pill><div style={{marginTop: 35, fontSize: 48, fontWeight: 950}}>支付宝 · 联接</div><div style={{marginTop: 22, fontSize: 33, color: C.gray, fontWeight: 850}}>申购赎回 · 等两天</div></Panel><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 650, height: 330}}><Pill bg={C.blue} style={{color: C.cream}}>场内</Pill><div style={{marginTop: 35, fontSize: 48, fontWeight: 950}}>券商 · 同花顺</div><div style={{marginTop: 22, fontSize: 33, color: C.gray, fontWeight: 850}}>实时交易 · 更自由</div></Panel></div><div style={{marginTop: 60, textAlign: 'center', ...inView(110)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 42}}>网格要的是：便宜 + 自由</Pill></div></Content></Frame>;

  if (kind === 15) return <Frame page={page} kicker="场内 · 场外 · 具体区别" title={<>做网格，<Mark color={C.blue}>只能买场内</Mark></>} subtitle="因为它能实时交易，买卖更便宜也更自由。" accent={C.blue} titleSize={95}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 28, ...inView(18)}}><Panel bg={C.paleYellow} shadow={`10px 12px 0 ${C.yellow}`} style={{width: 560, height: 350, textAlign: 'center'}}><div style={{fontSize: 45, fontWeight: 950}}>场外ETF</div><div style={{fontSize: 67, color: C.yellow, fontWeight: 950, margin: '38px 0 24px'}}>等两天</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>支付宝 · 联接</div></Panel><Panel bg={C.paleBlue} shadow={`10px 12px 0 ${C.blue}`} style={{width: 560, height: 350, textAlign: 'center'}}><div style={{fontSize: 45, fontWeight: 950}}>场内ETF</div><div style={{fontSize: 67, color: C.blue, fontWeight: 950, margin: '38px 0 24px'}}>实时买卖</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>券商 · 同花顺</div></Panel></div><div style={{marginTop: 55, display: 'flex', justifyContent: 'center', gap: 22, ...inView(115)}}><Pill bg={C.yellow} style={{fontSize: 40}}>更便宜</Pill><Arrow color={C.blue}>+</Arrow><Pill bg={C.blue} style={{color: C.cream, fontSize: 40}}>更自由</Pill></div></Content></Frame>;

  if (kind === 14) return <Frame page={page} kicker="手续费 · 很多人忽略的成本" title={<>做网格，<Mark color={C.yellow}>免5很关键</Mark></>} subtitle="每笔万2.3以上，还有最低5块的限制，天天触发会很贵。" accent={C.yellow} titleSize={92}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 36, ...inView(18)}}><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 520, height: 335, textAlign: 'center'}}><div style={{fontSize: 42, fontWeight: 950}}>买 ¥1000</div><div style={{fontSize: 90, color: C.blue, fontWeight: 950, margin: '28px 0'}}>¥5</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>最低收费</div></Panel><Arrow color={C.blue}>→</Arrow><Panel bg={C.paleBlue} shadow={`11px 13px 0 ${C.blue}`} style={{width: 650, height: 335, textAlign: 'center'}}><div style={{fontSize: 42, fontWeight: 950}}>免5 + 万0.5</div><div style={{fontSize: 90, color: C.blue, fontWeight: 950, margin: '28px 0'}}>¥0.5</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>买 ¥1万，只收5毛</div></Panel></div><div style={{marginTop: 54, textAlign: 'center', ...inView(120)}}><Pill bg={C.yellow} style={{fontSize: 40}}>频繁触发，手续费也要纳入规则</Pill></div></Content></Frame>;

  if (kind === 18) return <Frame page={page} kicker="手续费 · 找到合适费率" title={<>免5之后，<Mark color={C.blue}>费率也要谈</Mark></>} subtitle="万0.5左右，频繁买卖时才不会被成本拖住。" accent={C.blue} titleSize={92}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 34, ...inView(18)}}><Panel bg={C.white} shadow={`11px 13px 0 ${C.blue}`} style={{width: 480, height: 300, textAlign: 'center'}}><div style={{fontSize: 45, fontWeight: 950}}>普通账户</div><div style={{fontSize: 75, color: C.blue, fontWeight: 950, margin: '36px 0 18px'}}>万2.3+</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>还有最低5块</div></Panel><Arrow color={C.yellow}>→</Arrow><Panel bg={C.paleYellow} shadow={`11px 13px 0 ${C.yellow}`} style={{width: 650, height: 300, textAlign: 'center'}}><div style={{fontSize: 45, fontWeight: 950}}>免5账户</div><div style={{fontSize: 75, color: C.blue, fontWeight: 950, margin: '36px 0 18px'}}>万0.5</div><div style={{fontSize: 31, color: C.gray, fontWeight: 850}}>买1万只收5毛</div></Panel></div><div style={{marginTop: 58, textAlign: 'center', ...inView(110)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 39}}>不同营业部规则不同，最好有人引荐</Pill></div></Content></Frame>;

  if (kind === 19) return <Frame page={page} kicker="开户 · 最后一件实操" title={<>需要渠道？<Mark color={C.yellow}>私信我：开户</Mark></>} subtitle="我把合适的开户渠道发给你。" accent={C.yellow} titleSize={98}><Content><div style={{display: 'flex', justifyContent: 'center', ...inView(18)}}><Panel bg={C.paleYellow} shadow={`12px 14px 0 ${C.yellow}`} style={{width: 950, height: 300, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 54, fontWeight: 950}}>场内ETF</div><div style={{fontSize: 44, color: C.blue, fontWeight: 950, marginTop: 24}}>实时交易 · 费率更低 · 更适合网格</div></Panel></div><div style={{marginTop: 68, textAlign: 'center', ...inView(110)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 48}}>私信两个字：开户</Pill></div></Content></Frame>;

  if (kind === 20) return <Frame page={page} kicker="ETF网格交易 · 结尾" title={<>规则先想清楚，<Mark color={C.yellow}>再开始网格</Mark></>} subtitle="这期就到这里。" accent={C.blue} titleSize={94}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 35, ...inView(18)}}><div style={{fontSize: 82, fontWeight: 950, color: C.blue}}>震荡</div><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 82, fontWeight: 950}}>规则</div><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 82, fontWeight: 950, color: C.blue}}>执行</div></div><div style={{marginTop: 65, textAlign: 'center', ...inView(100)}}><Pill bg={C.yellow} style={{fontSize: 43}}>你现在有没有在做网格？</Pill></div><div style={{marginTop: 28, textAlign: 'center', ...inView(145)}}><Pill bg={C.blue} style={{color: C.cream, fontSize: 39}}>效果怎么样，评论区聊聊</Pill></div><div style={{marginTop: 28, textAlign: 'center', ...inView(190)}}><div style={{fontSize: 32, color: C.gray, fontWeight: 850}}>我是剑平，我们下期再见</div></div></Content></Frame>;

  return <Frame page={page} kicker="ETF网格交易 · 结尾" title={<>规则先想清楚，<Mark color={C.yellow}>再开始网格</Mark></>} subtitle="你现在有没有在做网格？效果怎么样，评论区聊聊。" accent={C.blue} titleSize={94}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 35, ...inView(18)}}><div style={{fontSize: 82, fontWeight: 950, color: C.blue}}>震荡</div><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 82, fontWeight: 950}}>规则</div><Arrow color={C.yellow}>→</Arrow><div style={{fontSize: 82, fontWeight: 950, color: C.blue}}>执行</div></div><div style={{marginTop: 75, textAlign: 'center', ...inView(110)}}><Pill bg={C.yellow} style={{fontSize: 43}}>我是剑平，我们下期再见</Pill></div></Content></Frame>;
};

const SCENE_KINDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 11, 17, 12, 13, 15, 14, 18, 19, 20];
export const ETFGridTradingVideo: React.FC = () => <AbsoluteFill style={{background: C.cream}}><Audio src={staticFile('etf-grid-trading.mp3')} /><Sequence from={0} durationInFrames={TOTAL_FRAMES} layout="none">{SCENE_STARTS.map((start, index) => <Sequence key={start} from={start} durationInFrames={SCENE_FRAMES[index]} layout="none"><PageSfx /><SceneSfx kind={SCENE_KINDS[index]} /><SceneVisual kind={SCENE_KINDS[index]} page={index + 1} /></Sequence>)}</Sequence><CaptionOverlay /></AbsoluteFill>;
