import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {C, appear, rise, settle} from './scenes/buffett/Shared';

const FONT = '"PingFang SC", "Noto Sans CJK SC", "Microsoft YaHei", Arial, sans-serif';

type PageFrameProps = {
  page: string;
  kicker: string;
  accent?: string;
  title: React.ReactNode;
  subtitle?: React.ReactNode;
  children: React.ReactNode;
};

const PageFrame: React.FC<PageFrameProps> = ({page, kicker, accent = C.orange, title, subtitle, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', inset: 0, opacity: 0.75, backgroundImage: 'linear-gradient(rgba(24,24,24,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(24,24,24,0.08) 1px, transparent 1px)', backgroundSize: '48px 48px'}} />
    <div style={{position: 'absolute', left: -70, top: 300, width: 160, height: 160, border: `18px solid ${accent}`, borderRadius: 42, rotate: '-12deg', opacity: 0.6}} />
    <div style={{position: 'absolute', right: -112, bottom: -150, width: 440, height: 440, borderRadius: '50%', background: accent, opacity: 0.7}} />
    <div style={{position: 'absolute', left: 126, top: 68, display: 'flex', alignItems: 'center', gap: 16, color: accent, fontSize: 24, fontWeight: 950, letterSpacing: 4, opacity: appear(frame, 0, 12)}}><span style={{display: 'inline-block', width: 42, height: 12, background: accent}} />{kicker}</div>
    <div style={{position: 'absolute', right: 126, top: 68, color: '#555', fontSize: 21, fontWeight: 900, letterSpacing: 4, opacity: appear(frame, 0, 12)}}>{page} / 20</div>
    <div style={{position: 'absolute', left: 126, right: 126, top: 126, opacity: appear(frame, 8, 18), translate: `0px ${rise(frame, 8)}px`}}>
      <div style={{fontSize: 82, lineHeight: 1.1, fontWeight: 950, letterSpacing: -3}}>{title}</div>
      {subtitle && <div style={{marginTop: 20, fontSize: 32, lineHeight: 1.3, color: C.gray, fontWeight: 750}}>{subtitle}</div>}
    </div>
    {children}
  </AbsoluteFill>;
};

const Card: React.FC<{children: React.ReactNode; x: number; y: number; width: number; height: number; bg?: string; shadow?: string; style?: React.CSSProperties}> = ({children, x, y, width, height, bg = '#FFFDF7', shadow = `9px 11px 0 ${C.blue}`, style}) => <div style={{position: 'absolute', left: x, top: y, width, height, boxSizing: 'border-box', padding: '28px 34px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 24, boxShadow: shadow, ...style}}>{children}</div>;

const Pill: React.FC<{children: React.ReactNode; bg?: string; style?: React.CSSProperties}> = ({children, bg = C.green, style}) => <div style={{display: 'inline-block', padding: '9px 18px', border: `3px solid ${C.ink}`, borderRadius: 999, background: bg, fontSize: 24, fontWeight: 950, ...style}}>{children}</div>;

const Arrow: React.FC<{children?: React.ReactNode; color?: string}> = ({children = '→', color = C.orange}) => <span style={{fontSize: 64, lineHeight: 1, color, fontWeight: 950}}>{children}</span>;

const FourQuestionPage: React.FC = () => {
  const frame = useCurrentFrame();
  const items = ['这公司靠什么赚钱？', '护城河能撑多久？', '5年后的盈利能估出来吗？', '估不出来怎么办？'];
  const focus = Math.min(3, Math.floor(interpolate(frame, [40, 440], [0, 4], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})));
  return <PageFrame page="04" kicker="选股之前 · 4个问题" accent={C.blue} title="买入之前，先问这4个问题" subtitle="这四个问题还没问完，页面不会提前翻走。">
    <div style={{position: 'absolute', left: 126, right: 126, top: 350, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 30}}>{items.map((item, index) => <Card key={item} x={0} y={0} width={0} height={0} style={{position: 'relative', left: 0, top: 0, width: 'auto', height: 210, padding: '34px 40px', background: index === focus ? C.paleGreen : '#FFFDF7', boxShadow: `${index === focus ? 10 : 7}px ${index === focus ? 12 : 9}px 0 ${index === focus ? C.orange : C.blue}`, opacity: appear(frame, 35 + index * 28, 16), scale: index === focus ? 1.025 : 1}}><div style={{display: 'flex', alignItems: 'center', gap: 22}}><div style={{width: 64, height: 64, borderRadius: '50%', border: `3px solid ${C.ink}`, background: index === 3 ? C.orange : C.green, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 26, fontWeight: 950}}>0{index + 1}</div><div style={{fontSize: 34, fontWeight: 950}}>{item}</div></div><div style={{position: 'absolute', left: 42, bottom: 28, width: `${48 + index * 12}%`, height: 4, borderRadius: 4, background: C.ink, opacity: 0.16}} /></Card>)}</div>
  </PageFrame>;
};

const FourAdvantagesPage: React.FC = () => {
  const frame = useCurrentFrame();
  const items = [['01', '全身心研究企业', C.blue], ['02', '保险浮存金撑底', C.green], ['03', '恐慌中敢砸巨资', C.orange], ['04', '没有赎回压力', '#E4C9FF']];
  return <PageFrame page="07" kicker="巴菲特的4个优势" accent={C.orange} title="这4个优势，普通人很难复制" subtitle="旁白会依次讲完四点，四张卡片持续留在屏幕上。">
    <div style={{position: 'absolute', left: 126, right: 126, top: 350, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 28}}>{items.map(([num, label, color], index) => <Card key={num} x={0} y={0} width={0} height={0} style={{position: 'relative', left: 0, top: 0, width: 'auto', height: 220, padding: '32px 38px', background: index % 2 === 0 ? '#FFFDF7' : '#F3FCDD', boxShadow: `8px 10px 0 ${color}`, opacity: appear(frame, 28 + index * 42, 18), translate: `0px ${rise(frame, 28 + index * 42)}px`}}><div style={{display: 'flex', alignItems: 'center', gap: 22}}><div style={{width: 62, height: 62, borderRadius: '50%', border: `3px solid ${C.ink}`, background: color, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 25, fontWeight: 950}}>{num}</div><div style={{fontSize: 34, fontWeight: 950}}>{label}</div></div><div style={{marginTop: 28, fontSize: 25, color: C.gray, fontWeight: 750}}>{index === 0 ? '把时间全部用在理解生意上' : index === 1 ? '资金结构让他能长期持有' : index === 2 ? '别人害怕时，他有能力下注' : '不用因为短期波动被迫卖出'}</div></Card>)}</div>
  </PageFrame>;
};

const PrecisePage: React.FC<{kind: number}> = ({kind}) => {
  const frame = useCurrentFrame();
  const reveal = (from: number, duration = 18) => ({opacity: appear(frame, from, duration), translate: `0px ${rise(frame, from)}px`});
  if (kind === 1) return <PageFrame page="01" kicker="巴菲特 · 指数基金" title={<>巴菲特一辈子都在挑公司，<br/><span style={{position: 'relative'}}>却建议普通人买指数？<i style={{position: 'absolute', left: 6, right: 0, bottom: -4, height: 18, background: C.orange, borderRadius: 8, zIndex: -1}} /></span></>} subtitle="一个特别有意思的矛盾，先把问题摆在桌面上。"><div style={{position: 'absolute', left: 126, top: 460, display: 'flex', gap: 150, ...reveal(45)}}><Card x={0} y={0} width={640} height={240} bg="#FFFDF7" shadow={`9px 11px 0 ${C.blue}`} style={{position: 'relative', left: 0, top: 0}}><Pill bg={C.green}>他自己</Pill><div style={{marginTop: 26, fontSize: 43, fontWeight: 950}}>挑公司 · 集中持股</div></Card><div style={{alignSelf: 'center'}}><Arrow /></div><Card x={0} y={0} width={640} height={240} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={{position: 'relative', left: 0, top: 0}}><Pill bg={C.orange}>给普通人</Pill><div style={{marginTop: 26, fontSize: 43, fontWeight: 950}}>低成本标普500</div></Card></div></PageFrame>;
  if (kind === 2) return <PageFrame page="02" kicker="先别急着下结论" title="是不是听着像：我能选股，你们不配？" subtitle="其实，这句话背后藏着巴菲特最清醒的认知。"><Card x={126} y={390} width={1668} height={260} bg={C.paleOrange} shadow={`10px 12px 0 ${C.orange}`} style={reveal(30)}><div style={{fontSize: 56, fontWeight: 950, textAlign: 'center'}}>这不是优越感，是能力边界。</div><div style={{marginTop: 22, textAlign: 'center', fontSize: 30, color: C.gray, fontWeight: 750}}>先说结论：巴菲特从没说选股无效。</div></Card><div style={{position: 'absolute', left: 126, right: 126, top: 760, textAlign: 'center', ...reveal(180)}}><Pill bg={C.green} style={{fontSize: 32}}>真正的问题是：你有没有研究优势？</Pill></div></PageFrame>;
  if (kind === 3) return <PageFrame page="03" kicker="选股有门槛" title="真正懂企业的人，才适合集中持股" subtitle="懂企业、能判断价格、还能拿得住十年，三件事缺一不可。"><div style={{position: 'absolute', left: 126, right: 126, top: 385, display: 'flex', justifyContent: 'space-between', ...reveal(28)}}>{['懂企业', '能判断价格', '拿得住十年'].map((label, index) => <Card key={label} x={0} y={0} width={490} height={235} bg={index === 1 ? C.paleGreen : '#FFFDF7'} shadow={`8px 10px 0 ${index === 1 ? C.orange : C.blue}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 51, fontWeight: 950}}>{index + 1}</div><div style={{marginTop: 24, fontSize: 34, fontWeight: 950}}>{label}</div></Card>)}</div><div style={{position: 'absolute', left: 126, right: 126, top: 720, textAlign: 'center', ...reveal(170)}}><Pill style={{fontSize: 32, padding: '14px 24px'}} bg={C.green}>没有研究优势的大多数人 → 买指数，成本更低，犯错更少</Pill></div></PageFrame>;
  if (kind === 4) return <FourQuestionPage />;
  if (kind === 5) return <PageFrame page="05" kicker="能力圈" title="估不出来怎么办？" subtitle="如果回答不出，就直接看下一家。承认不知道，也是一种能力。"><div style={{position: 'absolute', left: 126, right: 126, top: 410, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 50, ...reveal(25)}}><Card x={0} y={0} width={580} height={250} bg="#FFFDF7" shadow={`9px 11px 0 ${C.blue}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 34, fontWeight: 950}}>回答不出</div><div style={{marginTop: 26, fontSize: 52, color: C.orange, fontWeight: 950}}>继续看</div></Card><Arrow /><Card x={0} y={0} width={580} height={250} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 34, fontWeight: 950}}>在能力圈内</div><div style={{marginTop: 26, fontSize: 52, color: '#548500', fontWeight: 950}}>做决定</div></Card></div><div style={{position: 'absolute', left: 126, right: 126, top: 770, textAlign: 'center', ...reveal(170)}}><Pill bg={C.green} style={{fontSize: 33}}>知道自己不知道什么，本身就是能力</Pill></div></PageFrame>;
  if (kind === 6) return <PageFrame page="06" kicker="两类投资者" title="投资者，其实可以分成两类" subtitle="不懂企业，买指数；真懂企业，才考虑集中。"><Card x={126} y={370} width={760} height={360} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={reveal(28)}><Pill bg={C.orange}>01 · 不懂企业</Pill><div style={{marginTop: 32, fontSize: 43, fontWeight: 950}}>想长期拥有美国企业</div><div style={{marginTop: 24, fontSize: 29, color: C.gray, fontWeight: 750}}>去买指数基金</div></Card><Card x={1034} y={370} width={760} height={360} bg="#FFFDF7" shadow={`9px 11px 0 ${C.blue}`} style={reveal(85)}><Pill bg={C.green}>02 · 真懂企业</Pill><div style={{marginTop: 32, fontSize: 43, fontWeight: 950}}>可以集中持股</div><div style={{marginTop: 24, fontSize: 29, color: C.gray, fontWeight: 750}}>5到10家公司就够了</div></Card></PageFrame>;
  if (kind === 7) return <FourAdvantagesPage />;
  if (kind === 8) return <PageFrame page="08" kicker="主动基金 · 数学题" title="主动基金加在一起，拿到的就是市场本身" subtitle="扣除成本以前，有人跑赢，就有人跑输。"><div style={{position: 'absolute', left: 126, top: 410, width: 760, ...reveal(25)}}><div style={{fontSize: 42, fontWeight: 950, marginBottom: 32}}>主动基金总和</div><div style={{height: 90, border: `4px solid ${C.ink}`, borderRadius: 18, background: C.blue, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 42, fontWeight: 950}}>＝ 市场本身</div><div style={{marginTop: 30, fontSize: 30, color: C.gray, fontWeight: 750}}>平均收益不可能凭空超过市场。</div></div><Card x={1000} y={385} width={794} height={370} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={reveal(100)}><Pill bg={C.orange}>还要再扣一层</Pill><div style={{marginTop: 28, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20}}>{['管理费', '佣金', '税收', '情绪损耗'].map((x) => <div key={x} style={{padding: '14px 18px', border: `3px solid ${C.ink}`, borderRadius: 13, background: '#FFFDF7', fontSize: 28, fontWeight: 900}}>{x}</div>)}</div><div style={{marginTop: 26, fontSize: 30, fontWeight: 950}}>主动的整体，必然落后市场平均。</div></Card></PageFrame>;
  if (kind === 9) return <PageFrame page="09" kicker="盯盘 vs 躺平" title="辛辛苦苦每天盯盘，还不如躺平买指数？" subtitle="获取平均收益，有时反而更靠谱。"><div style={{position: 'absolute', left: 126, right: 126, top: 420, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 90, ...reveal(25)}}><Card x={0} y={0} width={620} height={250} bg="#FFFDF7" shadow={`9px 11px 0 ${C.blue}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 37, fontWeight: 950}}>每天盯盘</div><div style={{marginTop: 26, fontSize: 27, color: C.gray, fontWeight: 750}}>研究、交易、情绪消耗</div></Card><Arrow color={C.orange}>≠</Arrow><Card x={0} y={0} width={620} height={250} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 37, fontWeight: 950}}>买指数</div><div style={{marginTop: 26, fontSize: 27, color: C.gray, fontWeight: 750}}>简单、便宜、容易坚持</div></Card></div></PageFrame>;
  if (kind === 10) return <PageFrame page="10" kicker="2007 · 赌约" title="十年之后，数字把“平均”说得很直白" subtitle="标普500：125.8%；主动基金经理最好：87.7%。"><div style={{position: 'absolute', left: 126, right: 126, top: 400, ...reveal(25)}}><div style={{display: 'flex', alignItems: 'center', gap: 24, margin: '28px 0'}}><div style={{width: 160, fontSize: 31, fontWeight: 950}}>标普500</div><div style={{height: 72, flex: 1, border: `3px solid ${C.ink}`, borderRadius: 14, background: '#FFFDF7', overflow: 'hidden'}}><div style={{width: `${interpolate(frame, [30, 220], [0, 100], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, height: '100%', background: C.green}} /></div><div style={{width: 220, fontSize: 64, fontWeight: 950}}>125.8%</div></div><div style={{display: 'flex', alignItems: 'center', gap: 24, margin: '28px 0'}}><div style={{width: 160, fontSize: 31, fontWeight: 950}}>最佳主动</div><div style={{height: 72, flex: 1, border: `3px solid ${C.ink}`, borderRadius: 14, background: '#FFFDF7', overflow: 'hidden'}}><div style={{width: `${interpolate(frame, [50, 250], [0, 70], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, height: '100%', background: C.orange}} /></div><div style={{width: 220, fontSize: 64, fontWeight: 950}}>87.7%</div></div></div></PageFrame>;
  if (kind === 11) return <PageFrame page="11" kicker="2025 · 更直白" title="79%的美国大型主动基金，跑输标普500" subtitle="这不是偶然的一年，而是长期重复出现的结果。"><div style={{position: 'absolute', left: 260, right: 260, top: 420, ...reveal(25)}}><div style={{height: 86, border: `4px solid ${C.ink}`, borderRadius: 18, background: '#FFFDF7', overflow: 'hidden'}}><div style={{width: `${interpolate(frame, [30, 150], [0, 79], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, height: '100%', background: C.orange}} /></div><div style={{marginTop: 30, display: 'flex', justifyContent: 'space-between', fontSize: 28, fontWeight: 900}}><span>跑输</span><span>79%</span></div><div style={{marginTop: 70, textAlign: 'center'}}><Pill bg={C.green} style={{fontSize: 34}}>选择平均，不等于选择平庸</Pill></div></div></PageFrame>;
  if (kind === 12) return <PageFrame page="12" kicker="指数基金 · 运行机制" title="其实就6个字：不去猜测市场" subtitle="按照市值加权，自动分散，把“谁更强”交给时间筛选。"><div style={{position: 'absolute', left: 126, top: 390, width: 720, ...reveal(25)}}>{['公司A', '公司B', '公司C', '公司D'].map((label, index) => <div key={label} style={{display: 'flex', alignItems: 'center', gap: 16, margin: '20px 0'}}><div style={{width: 110, fontSize: 25, fontWeight: 900}}>{label}</div><div style={{height: 38, flex: 1, border: `3px solid ${C.ink}`, borderRadius: 9, background: '#E6E6DD', overflow: 'hidden'}}><div style={{width: `${[64, 44, 25, 14][index]}%`, height: '100%', background: [C.orange, C.blue, C.green, '#DDD'][index]}} /></div></div>)}</div><Card x={980} y={386} width={814} height={360} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={reveal(90)}><Pill bg={C.orange}>自动发生</Pill><div style={{marginTop: 28, fontSize: 38, fontWeight: 950}}>厉害的公司不断变大权重</div><div style={{marginTop: 20, fontSize: 38, fontWeight: 950}}>弱一点的公司自动被替换</div><div style={{marginTop: 24, fontSize: 26, color: C.gray, fontWeight: 750}}>你不需要押中下一家伟大公司。</div></Card></PageFrame>;
  if (kind === 13) return <PageFrame page="13" kicker="巴菲特给妻子的信托" title="90%标普500 + 10%短期国债" subtitle="简单配置，长期持有。"><div style={{position: 'absolute', left: 126, right: 126, top: 390, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 55, ...reveal(25)}}><div style={{width: 390, height: 390, borderRadius: '50%', border: `5px solid ${C.ink}`, background: `conic-gradient(${C.green} 0deg 324deg, ${C.blue} 324deg 360deg)`, display: 'flex', alignItems: 'center', justifyContent: 'center'}}><div style={{width: 226, height: 226, borderRadius: '50%', background: C.paper, border: `3px solid ${C.ink}`, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center'}}><div style={{fontSize: 64, fontWeight: 950}}>90/10</div><div style={{fontSize: 22, fontWeight: 900}}>配置</div></div></div><div style={{display: 'flex', flexDirection: 'column', gap: 24}}><Pill bg={C.green} style={{fontSize: 34}}>90% 标普500</Pill><Pill bg={C.blue} style={{fontSize: 34}}>10% 短期国债</Pill></div></div></PageFrame>;
  if (kind === 14) return <PageFrame page="14" kicker="普通人的好处 · 01" title="把问题变简单" subtitle="选股要判断公司、管理层、估值。买指数，只需要相信国运。"><div style={{position: 'absolute', left: 126, right: 126, top: 425, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 28, ...reveal(25)}}>{['公司', '管理层', '估值'].map((label) => <Pill key={label} bg="#FFFDF7" style={{fontSize: 33}}>{label}</Pill>)}<Arrow /><Pill bg={C.green} style={{fontSize: 35}}>相信国运</Pill></div></PageFrame>;
  if (kind === 15) return <PageFrame page="15" kicker="普通人的好处 · 02" title="成本更低，复利更有力量" subtitle="费率在买入之前就能锁定，每年少扣一点，长期下来就是天壤之别。"><div style={{position: 'absolute', left: 250, right: 250, top: 420, display: 'flex', alignItems: 'end', justifyContent: 'center', gap: 62, ...reveal(25)}}>{[140, 210, 300, 405, 530].map((height, index) => <div key={height} style={{width: 130, height, border: `3px solid ${C.ink}`, borderRadius: '12px 12px 0 0', background: index === 4 ? C.green : C.blue, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24, fontWeight: 950}}>{index + 1}年</div>)}</div><div style={{position: 'absolute', left: 126, right: 126, top: 790, textAlign: 'center', ...reveal(130)}}><Pill bg={C.orange} style={{fontSize: 32}}>小费率 × 长时间 = 巨大的差距</Pill></div></PageFrame>;
  if (kind === 16) return <PageFrame page="16" kicker="风险提醒" title="指数不消灭波动" subtitle="巴菲特自己也跌过50%。不能承受浮亏的钱，就别全放股市。"><Card x={260} y={390} width={1400} height={280} bg="#FFFDF7" shadow={`10px 12px 0 ${C.blue}`} style={reveal(25)}><div style={{fontSize: 30, color: C.gray, fontWeight: 850}}>浮亏承受力</div><div style={{marginTop: 20, fontSize: 92, fontWeight: 950, color: C.orange}}>-50%</div><div style={{position: 'absolute', left: 40, right: 40, bottom: 32, height: 18, borderRadius: 12, background: '#E4E4DC', overflow: 'hidden'}}><div style={{width: `${interpolate(frame, [40, 180], [0, 50], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, height: '100%', background: C.orange}} /></div></Card></PageFrame>;
  if (kind === 17) return <PageFrame page="17" kicker="买之前再看两眼" title="场内溢价 + 跟踪误差" subtitle="如果溢价太高，就是好指数，也可能赚不到钱。"><div style={{position: 'absolute', left: 126, right: 126, top: 410, display: 'flex', justifyContent: 'center', gap: 34, ...reveal(25)}}><Card x={0} y={0} width={740} height={280} bg={C.paleGreen} shadow={`9px 11px 0 ${C.orange}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 38, fontWeight: 950}}>场内溢价</div><div style={{marginTop: 24, fontSize: 28, color: C.gray, fontWeight: 750}}>价格可能比真实价值贵</div></Card><Card x={0} y={0} width={740} height={280} bg="#FFFDF7" shadow={`9px 11px 0 ${C.blue}`} style={{position: 'relative', left: 0, top: 0}}><div style={{fontSize: 38, fontWeight: 950}}>跟踪误差</div><div style={{marginTop: 24, fontSize: 28, color: C.gray, fontWeight: 750}}>基金不一定完全跟住指数</div></Card></div></PageFrame>;
  if (kind === 18) return <PageFrame page="18" kicker="如果你不想研究溢价" title="实在不知道怎么看？" subtitle="那就买场外的。先把选择做简单。"><div style={{position: 'absolute', left: 126, right: 126, top: 400, textAlign: 'center', ...reveal(25)}}><div style={{fontSize: 75, fontWeight: 950, color: C.orange}}>买场外</div><div style={{marginTop: 30, fontSize: 35, fontWeight: 850}}>把复杂的检查，交给更简单的入口。</div></div></PageFrame>;
  if (kind === 19) return <PageFrame page="19" kicker="轮到你了" title="你是主动选股，还是被动指数？" subtitle="欢迎在评论区聊聊你的选择。"><div style={{position: 'absolute', left: 126, right: 126, top: 430, display: 'flex', justifyContent: 'center', gap: 55, ...reveal(25)}}><Pill bg={C.orange} style={{fontSize: 43, padding: '20px 42px'}}>主动选股</Pill><div style={{fontSize: 55, fontWeight: 950, color: C.gray}}>还是</div><Pill bg={C.green} style={{fontSize: 43, padding: '20px 42px'}}>被动指数</Pill></div></PageFrame>;
  return <PageFrame page="20" kicker="结尾" title="别忘了点赞、收藏、关注" subtitle="下期见。"><div style={{position: 'absolute', left: 126, right: 126, top: 430, textAlign: 'center', ...reveal(25)}}><Pill bg={C.green} style={{fontSize: 46, padding: '20px 42px'}}>把复杂的投资，讲得更简单</Pill></div></PageFrame>;
};

const PAGE_STARTS = [0, 444, 855, 1170, 1638, 2013, 2475, 2961, 3408, 3629, 4164, 4365, 4881, 5196, 5478, 5685, 5961, 6330, 6468, 6684];
const PAGE_DURATIONS = PAGE_STARTS.map((start, index) => (PAGE_STARTS[index + 1] ?? 6840) - start);

export const PreciseBuffettVideo: React.FC = () => <AbsoluteFill style={{background: C.paper}}>
  <Audio src={staticFile('buffett-index-intro.mp3')} />
  {PAGE_STARTS.map((from, index) => <Sequence key={index} from={from} durationInFrames={PAGE_DURATIONS[index]} name={`第${String(index + 1).padStart(2, '0')}页`}><PrecisePage kind={index + 1} /></Sequence>)}
</AbsoluteFill>;
