import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill, Easing, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {C} from './scenes/buffett/Shared';

const FONT = '"PingFang SC", "Noto Sans CJK SC", "Microsoft YaHei", Arial, sans-serif';

// These boundaries are taken from the supplied SRT. Each scene starts on a
// natural subtitle group boundary, so the visual never advances mid-thought.
const SCENE_STARTS = [0, 11.9, 20.3, 33.5, 40.066, 45.266, 54.4, 61.5, 73.166, 82.466, 92, 99.133, 110.166, 121.366, 131, 138.666, 145.966, 154.533, 163.066, 171.3, 176.933, 185.7, 193.333, 203.266, 211.6, 215.966, 218.9, 224.766];
const TOTAL_FRAMES = 6840;
const SCENE_FRAMES = SCENE_STARTS.map((start, index) => index === SCENE_STARTS.length - 1 ? TOTAL_FRAMES - Math.round(start * 30) : Math.round((SCENE_STARTS[index + 1] - start) * 30));
const SCENE_KINDS = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27];

const fade = (frame: number, delay = 0, duration = 18) => interpolate(frame, [delay, delay + duration], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic)});
const rise = (frame: number, delay = 0, distance = 26) => interpolate(frame, [delay, delay + 18], [distance, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp', easing: Easing.out(Easing.cubic)});
const enter = (frame: number, delay = 0, distance = 26) => ({opacity: fade(frame, delay), transform: `translateY(${rise(frame, delay, distance)}px)`});

const Mark: React.FC<{children: React.ReactNode; color?: string}> = ({children, color = C.green}) => <span style={{position: 'relative', zIndex: 0, display: 'inline-block'}}><span style={{position: 'absolute', left: -8, right: -8, bottom: 4, height: 19, borderRadius: 7, background: color, zIndex: -1}} />{children}</span>;

const Panel: React.FC<{children: React.ReactNode; bg?: string; shadow?: string; style?: React.CSSProperties}> = ({children, bg = '#FFFDF7', shadow = `10px 12px 0 ${C.blue}`, style}) => <div style={{boxSizing: 'border-box', padding: '34px 38px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 28, boxShadow: shadow, ...style}}>{children}</div>;

const Chip: React.FC<{children: React.ReactNode; bg?: string; style?: React.CSSProperties}> = ({children, bg = C.green, style}) => <div style={{display: 'inline-block', padding: '12px 24px', background: bg, border: `3px solid ${C.ink}`, borderRadius: 999, fontSize: 28, lineHeight: 1.1, fontWeight: 950, ...style}}>{children}</div>;

const Arrow: React.FC<{children?: React.ReactNode; color?: string}> = ({children = '→', color = C.orange}) => <div style={{fontSize: 76, lineHeight: 1, fontWeight: 950, color}}>{children}</div>;

type FrameProps = {page: number; kicker: string; accent?: string; title: React.ReactNode; subtitle?: React.ReactNode; titleSize?: number; children: React.ReactNode};

const Frame: React.FC<FrameProps> = ({page, kicker, accent = C.orange, title, subtitle, titleSize = 88, children}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', inset: 0, opacity: 0.72, backgroundImage: 'linear-gradient(rgba(24,24,24,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(24,24,24,0.08) 1px, transparent 1px)', backgroundSize: '48px 48px'}} />
    <div style={{position: 'absolute', left: -90, top: 310, width: 190, height: 190, border: `19px solid ${accent}`, borderRadius: 48, transform: 'rotate(-12deg)', opacity: 0.55}} />
    <div style={{position: 'absolute', right: -170, bottom: -205, width: 510, height: 510, borderRadius: '50%', background: accent, opacity: 0.68}} />
    <div style={{position: 'absolute', left: 126, top: 88, display: 'flex', alignItems: 'center', gap: 18, color: accent, fontSize: 31, fontWeight: 950, letterSpacing: 4, opacity: fade(frame, 0, 12)}}><span style={{display: 'inline-block', width: 52, height: 14, background: accent}} />{kicker}</div>
    <div style={{position: 'absolute', right: 126, top: 88, color: '#555', fontSize: 27, fontWeight: 900, letterSpacing: 4, opacity: fade(frame, 0, 12)}}>{String(page).padStart(2, '0')} / 28</div>
    <div style={{position: 'absolute', left: 126, right: 126, top: 166, opacity: fade(frame, 8, 18), transform: `translateY(${rise(frame, 8)}px)`}}>
      <div style={{fontSize: titleSize, lineHeight: 1.08, fontWeight: 950, letterSpacing: -4}}>{title}</div>
      {subtitle && <div style={{marginTop: 24, maxWidth: 1650, fontSize: 42, lineHeight: 1.28, color: C.gray, fontWeight: 800}}>{subtitle}</div>}
    </div>
    {children}
  </AbsoluteFill>;
};

const Content: React.FC<{children: React.ReactNode; style?: React.CSSProperties}> = ({children, style}) => <div style={{position: 'absolute', left: 126, right: 126, top: 420, bottom: 48, ...style}}>{children}</div>;

const PageSfx: React.FC<{page: number}> = ({page}) => <>
  <Audio src={staticFile('sfx/whoosh.mp3')} volume={0.36} />
</>;

const MOTION_TIMES: Record<number, number[]> = {
  1: [32, 145], 2: [20, 135], 3: [18, 120], 4: [18, 100], 5: [0, 20, 40, 60], 6: [20, 120], 7: [18, 80], 8: [20, 120], 9: [18, 50, 82, 114], 10: [24, 115], 11: [20, 95, 175], 12: [20, 120], 13: [20], 14: [20, 50], 15: [20, 100, 165], 16: [20, 125], 17: [18, 100], 18: [18], 19: [18], 20: [18, 120], 21: [18, 120], 22: [18, 130], 23: [18], 24: [18, 110], 25: [18, 100], 26: [18, 105], 27: [20],
};

const MotionSfx: React.FC<{at: number}> = ({at}) => <Sequence from={at} durationInFrames={28}><Audio src={staticFile('sfx/pop.mp3')} volume={0.39} /></Sequence>;
const SceneSfx: React.FC<{kind: number}> = ({kind}) => <>{(MOTION_TIMES[kind] ?? [20]).map((at) => <MotionSfx key={at} at={at} />)}</>;

const SceneVisual: React.FC<{kind: number; page: number}> = ({kind, page}) => {
  const frame = useCurrentFrame();
  const inView = (delay = 20, distance = 32) => enter(frame, delay, distance);

  if (kind === 1) return <Frame page={page} kicker="巴菲特 · 指数基金" title={<>巴菲特一辈子都在挑公司，<br /><Mark color={C.orange}>却建议普通人买指数？</Mark></>} subtitle="一个特别有意思的矛盾，先把问题摆在桌面上。" titleSize={84}><Content style={{top: 445}}><div style={{display: 'flex', alignItems: 'center', gap: 48, ...inView(32)}}><Panel style={{width: 710, height: 285}}><Chip>他自己</Chip><div style={{marginTop: 34, fontSize: 52, fontWeight: 950}}>挑公司 · 集中持股</div></Panel><Arrow /><Panel bg={C.paleGreen} shadow={`10px 12px 0 ${C.orange}`} style={{width: 710, height: 285}}><Chip bg={C.orange}>给普通人</Chip><div style={{marginTop: 34, fontSize: 52, fontWeight: 950}}>低成本标普500</div></Panel></div><div style={{marginTop: 52, ...inView(145)}}><Chip bg={C.blue} style={{fontSize: 34}}>hello，我是剑平</Chip></div></Content></Frame>;

  if (kind === 2) return <Frame page={page} kicker="先别急着下结论" title={<>是不是听着像：<Mark color={C.orange}>我能选股，你们不配？</Mark></>} subtitle="其实，这句话背后藏着巴菲特最清醒的认知。" titleSize={90}><Content><Panel bg={C.paleOrange} shadow={`12px 14px 0 ${C.orange}`} style={{height: 300, display: 'flex', flexDirection: 'column', justifyContent: 'center', textAlign: 'center', ...inView(20)}}><div style={{fontSize: 66, fontWeight: 950}}>这不是优越感，是能力边界。</div><div style={{marginTop: 24, fontSize: 38, color: C.gray, fontWeight: 800}}>今天用最短的时间，把这件事讲明白。</div></Panel><div style={{marginTop: 64, textAlign: 'center', ...inView(135)}}><Chip style={{fontSize: 38}}>真正的问题：你有没有研究优势？</Chip></div></Content></Frame>;

  if (kind === 3) return <Frame page={page} kicker="选股有门槛" title={<>真正懂企业的人，<Mark color={C.orange}>才适合集中持股</Mark></>} subtitle="三件事缺一不可：懂企业、能判断价格、还能拿得住十年。"><Content><div style={{display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 28, ...inView(18)}}>{[['01', '懂企业', C.green], ['02', '能判断价格', C.blue], ['03', '拿得住10年', C.orange]].map(([n, label, color]) => <Panel key={String(n)} bg={n === '02' ? C.paleGreen : '#FFFDF7'} shadow={`10px 12px 0 ${color}`} style={{height: 260}}><div style={{fontSize: 62, fontWeight: 950, color}}>{n}</div><div style={{marginTop: 24, fontSize: 42, fontWeight: 950}}>{label}</div></Panel>)}</div><div style={{marginTop: 58, textAlign: 'center', ...inView(120)}}><Chip bg={C.green} style={{fontSize: 35}}>大多数人 → 买指数 · 成本更低 · 犯错更少 · 更容易拿得住</Chip></div></Content></Frame>;

  if (kind === 4) return <Frame page={page} kicker="巴菲特 · 选股流程" title="那巴菲特自己是怎么选的？" subtitle="买入之前，他会先问四个问题。" titleSize={94}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 30, ...inView(18)}}>{['公司', '生意', '价格', '未来'].map((x, i) => <React.Fragment key={x}><Panel bg={[C.paleGreen, C.paleBlue, C.paleOrange, '#E9D7FF'][i]} shadow={`9px 11px 0 ${[C.green, C.blue, C.orange, '#A879E8'][i]}`} style={{width: 280, height: 210, textAlign: 'center', display: 'flex', alignItems: 'center', justifyContent: 'center'}}><div style={{fontSize: 43, fontWeight: 950}}>{x}</div></Panel>{i < 3 && <Arrow />}</React.Fragment>)}</div><div style={{marginTop: 70, textAlign: 'center', ...inView(100)}}><Chip bg={C.orange} style={{fontSize: 42, padding: '18px 38px'}}>买入之前，先问4个问题</Chip></div></Content></Frame>;

  if (kind === 5) {
    const items = ['这公司靠什么赚钱？', '护城河能撑多久？', '5年后的盈利能估出来吗？', '估不出来怎么办？'];
    const focus = Math.min(3, Math.floor(interpolate(frame, [0, 250], [0, 4], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})));
    return <Frame page={page} kicker="买入之前 · 4个问题" accent={C.blue} title={<>先问这4个问题，<Mark color={C.blue}>再决定买不买</Mark></>} subtitle="四个问题逐个出现、逐个高亮。" titleSize={86}><Content style={{top: 420}}><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 28}}>{items.map((item, index) => <Panel key={item} bg={index === focus ? C.paleGreen : '#FFFDF7'} shadow={`${index === focus ? 12 : 8}px ${index === focus ? 14 : 10}px 0 ${index === focus ? C.orange : C.blue}`} style={{height: 230, transform: `scale(${index === focus ? 1.03 : 1})`, opacity: fade(frame, index * 20, 16)}}><div style={{display: 'flex', alignItems: 'center', gap: 22}}><div style={{width: 70, height: 70, borderRadius: '50%', border: `3px solid ${C.ink}`, background: index === 3 ? C.orange : C.green, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28, fontWeight: 950}}>0{index + 1}</div><div style={{fontSize: 42, fontWeight: 950}}>{item}</div></div><div style={{position: 'absolute', left: 38, right: 38, bottom: 30, height: 7, borderRadius: 7, background: index === focus ? C.orange : '#D9D9D2', opacity: 0.7}} /></Panel>)}</div></Content></Frame>;
  }

  if (kind === 6) return <Frame page={page} kicker="能力圈" title={<>他自己不看指标，<Mark color={C.blue}>也不听分析师</Mark></>} subtitle="如果回答不出这4个问题，就直接看下一家。" titleSize={89}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 44, ...inView(20)}}><Panel style={{width: 750, height: 360, textAlign: 'center', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 58, fontWeight: 950, textDecoration: 'line-through', textDecorationThickness: 6}}>看指标</div><div style={{marginTop: 28, fontSize: 40, color: C.gray, fontWeight: 800}}>不把复杂数字当答案</div></Panel><Arrow>×</Arrow><Panel style={{width: 750, height: 360, textAlign: 'center', background: C.paleBlue, display: 'flex', flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 58, fontWeight: 950, textDecoration: 'line-through', textDecorationThickness: 6}}>听分析师</div><div style={{marginTop: 28, fontSize: 40, color: C.gray, fontWeight: 800}}>不把别人的判断当能力</div></Panel></div><div style={{marginTop: 72, textAlign: 'center', ...inView(120)}}><Chip bg={C.orange} style={{fontSize: 48, padding: '18px 34px'}}>回答不出 → 直接看下一家</Chip></div></Content></Frame>;

  if (kind === 7) return <Frame page={page} kicker="能力圈" title={<>承认自己不知道答案，<Mark color={C.green}>本身就是能力</Mark></>} subtitle="在自己的能力圈内做事，才是长期投资的起点。" titleSize={84}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 100, ...inView(18)}}><div style={{width: 350, height: 350, borderRadius: '50%', border: `6px solid ${C.ink}`, background: C.paleGreen, display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center', boxShadow: `12px 14px 0 ${C.green}`}}><div><div style={{fontSize: 52, fontWeight: 950}}>能力圈</div><div style={{marginTop: 12, fontSize: 30, fontWeight: 850}}>知道自己知道什么</div></div></div><div style={{maxWidth: 760, ...inView(80)}}><div style={{fontSize: 66, fontWeight: 950}}>投资者<br /><Mark color={C.blue}>分成两类</Mark></div><div style={{marginTop: 28, fontSize: 36, color: C.gray, fontWeight: 800}}>不懂企业，买指数；真懂企业，才考虑集中。</div></div></div></Content></Frame>;

  if (kind === 8) return <Frame page={page} kicker="两类投资者" title={<>不懂企业，买指数；<Mark color={C.orange}>真懂企业，才集中</Mark></>} subtitle="长期拥有美国企业，不一定要自己挑出下一家伟大公司。" titleSize={82}><Content><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 34, ...inView(20)}}><Panel bg={C.paleGreen} shadow={`11px 13px 0 ${C.orange}`} style={{height: 360}}><Chip bg={C.orange}>01 · 不懂企业</Chip><div style={{marginTop: 34, fontSize: 44, fontWeight: 950}}>想长期拥有美国企业</div><div style={{marginTop: 26, fontSize: 34, color: C.gray, fontWeight: 850}}>那就买指数基金</div></Panel><Panel shadow={`11px 13px 0 ${C.blue}`} style={{height: 360}}><Chip>02 · 真懂企业</Chip><div style={{marginTop: 34, fontSize: 44, fontWeight: 950}}>可以集中持股</div><div style={{marginTop: 26, fontSize: 34, color: C.gray, fontWeight: 850}}>5—10家公司就够了</div></Panel></div><div style={{marginTop: 52, textAlign: 'center', ...inView(120)}}><Chip bg={C.orange} style={{fontSize: 36}}>巴菲特显然属于后者</Chip></div></Content></Frame>;

  if (kind === 9) return <Frame page={page} kicker="巴菲特的4个优势" title={<>他的4个优势，<Mark color={C.orange}>普通人很难复制</Mark></>} subtitle="全身心研究企业、浮存金撑底、恐慌中敢下注、没有赎回压力。" titleSize={84}><Content style={{top: 415}}><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 28, ...inView(18)}}>{[['01', '全身心研究企业', '把时间全部用在理解生意上', C.blue], ['02', '保险浮存金撑底', '资金结构让他能长期持有', C.green], ['03', '恐慌中敢砸巨资', '别人害怕时，他有能力下注', C.orange], ['04', '没有赎回压力', '不用因为短期波动被迫卖出', '#B58CE8']].map(([n, title, body, color], index) => <Panel key={String(n)} bg={index % 2 ? '#F3FCDD' : '#FFFDF7'} shadow={`9px 11px 0 ${color}`} style={{height: 230, opacity: fade(frame, index * 32, 16), transform: `translateY(${rise(frame, index * 32)}px)`}}><div style={{display: 'flex', alignItems: 'center', gap: 20}}><div style={{width: 64, height: 64, borderRadius: '50%', border: `3px solid ${C.ink}`, background: color, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 25, fontWeight: 950}}>{n}</div><div style={{fontSize: 37, fontWeight: 950}}>{title}</div></div><div style={{marginTop: 28, fontSize: 26, color: C.gray, fontWeight: 800}}>{body}</div></Panel>)}</div></Content></Frame>;

  if (kind === 10) return <Frame page={page} kicker="主动基金 · 数学题" title={<>一条很冷酷的数学题：<Mark color={C.blue}>主动基金总和 = 市场本身</Mark></>} subtitle="市面上所有主动基金加在一起，持有的就是市场本身。" titleSize={76}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 36, ...inView(24)}}><Panel bg={C.paleOrange} shadow={`10px 12px 0 ${C.orange}`} style={{width: 620, height: 250, display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center'}}><div style={{fontSize: 49, fontWeight: 950}}>所有主动基金</div></Panel><Arrow>=</Arrow><Panel bg={C.paleGreen} shadow={`10px 12px 0 ${C.green}`} style={{width: 620, height: 250, display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center'}}><div style={{fontSize: 55, fontWeight: 950}}>市场本身</div></Panel></div><div style={{marginTop: 65, height: 92, border: `4px solid ${C.ink}`, borderRadius: 18, background: '#FFFDF7', overflow: 'hidden', ...inView(115)}}><div style={{height: '100%', width: `${interpolate(frame, [130, 240], [0, 100], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, background: C.blue}} /></div></Content></Frame>;

  if (kind === 11) return <Frame page={page} kicker="主动基金 · 成本" title={<>扣除成本之前，<Mark color={C.orange}>平均收益不可能超过市场</Mark></>} subtitle="有人跑赢，就有人跑输；再加上管理费、佣金、税收和情绪损耗。" titleSize={82}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 42, ...inView(20)}}><div style={{fontSize: 72, fontWeight: 950, color: C.green}}>有人跑赢</div><Arrow>↔</Arrow><div style={{fontSize: 72, fontWeight: 950, color: C.orange}}>有人跑输</div></div><div style={{marginTop: 70, display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 22, ...inView(95)}}>{['管理费', '佣金', '税收', '情绪损耗'].map((x, i) => <Panel key={x} bg={i % 2 ? C.paleBlue : C.paleOrange} shadow={`7px 9px 0 ${i % 2 ? C.blue : C.orange}`} style={{height: 145, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 32, fontWeight: 950}}>{x}</Panel>)}</div><div style={{marginTop: 55, textAlign: 'center', ...inView(175)}}><Chip bg={C.orange} style={{fontSize: 36}}>主动的整体，必然落后市场平均水平</Chip></div></Content></Frame>;

  if (kind === 12) return <Frame page={page} kicker="盯盘 vs 躺平" title={<>辛辛苦苦每天盯盘，<Mark color={C.green}>不如躺平买指数</Mark></>} subtitle="获取平均收益，有时反而更靠谱。" titleSize={86}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 60, ...inView(20)}}><Panel style={{width: 690, height: 310}}><Chip bg={C.orange}>每天盯盘</Chip><div style={{marginTop: 32, fontSize: 45, fontWeight: 950}}>研究 · 交易 · 情绪消耗</div></Panel><Arrow>≠</Arrow><Panel bg={C.paleGreen} shadow={`11px 13px 0 ${C.green}`} style={{width: 690, height: 310}}><Chip>买指数</Chip><div style={{marginTop: 32, fontSize: 45, fontWeight: 950}}>简单 · 便宜 · 容易坚持</div></Panel></div><div style={{marginTop: 62, textAlign: 'center', ...inView(120)}}><Chip bg={C.blue} style={{fontSize: 40}}>平均收益，靠谱就好</Chip></div></Content></Frame>;

  if (kind === 13) return <Frame page={page} kicker="2007 · 赌约" title={<>巴菲特做了一个<Mark color={C.orange}>非常出名的赌约</Mark></>} subtitle="他买标普500指数基金，对方用200多只对冲基金组成组合。" titleSize={91}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 46, ...inView(20)}}><Panel bg={C.paleGreen} shadow={`12px 14px 0 ${C.green}`} style={{width: 720, height: 340}}><Chip>巴菲特</Chip><div style={{marginTop: 32, fontSize: 50, fontWeight: 950}}>标普500指数基金</div><div style={{marginTop: 22, fontSize: 29, color: C.gray, fontWeight: 800}}>简单、透明、长期</div></Panel><Arrow>VS</Arrow><Panel shadow={`12px 14px 0 ${C.orange}`} style={{width: 720, height: 340}}><Chip bg={C.orange}>对方基金经理</Chip><div style={{marginTop: 32, fontSize: 50, fontWeight: 950}}>200多只对冲基金</div><div style={{marginTop: 22, fontSize: 29, color: C.gray, fontWeight: 800}}>复杂、主动、难复制</div></Panel></div></Content></Frame>;

  if (kind === 14) return <Frame page={page} kicker="十年之后 · 数字" title={<>数字把“平均”<Mark color={C.green}>说得很直白</Mark></>} subtitle="十年下来，指数涨了125.8%，主动基金经理最好才87.7%。" titleSize={92}><Content><div style={{...inView(20)}}>{[['标普500', 125.8, C.green], ['主动基金最好', 87.7, C.orange]].map(([label, value, color], index) => <div key={String(label)} style={{display: 'flex', alignItems: 'center', gap: 24, margin: '35px 0'}}><div style={{width: 230, fontSize: 35, fontWeight: 950}}>{label}</div><div style={{height: 82, flex: 1, border: `4px solid ${C.ink}`, borderRadius: 16, background: '#FFFDF7', overflow: 'hidden'}}><div style={{height: '100%', width: `${interpolate(frame, [30 + index * 30, 150 + index * 30], [0, Number(value) / 1.258], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, background: color}} /></div><div style={{width: 260, fontSize: 68, fontWeight: 950}}>{value}%</div></div>)}</div></Content></Frame>;

  if (kind === 15) return <Frame page={page} kicker="2025 · 更直白" title={<>79%的美国大型主动基金，<Mark color={C.orange}>跑输标普500</Mark></>} subtitle="这不是偶然的一年，而是长期重复出现的结果。" titleSize={83}><Content><div style={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 90, ...inView(20)}}><div style={{fontSize: 170, fontWeight: 950, color: C.orange}}>79%</div><div style={{fontSize: 55, fontWeight: 950}}>跑输</div><div style={{height: 200, width: 38, background: C.orange, borderRadius: 20}} /></div><div style={{marginTop: 65, height: 100, border: `4px solid ${C.ink}`, borderRadius: 20, background: '#FFFDF7', overflow: 'hidden', ...inView(100)}}><div style={{height: '100%', width: `${interpolate(frame, [110, 210], [0, 79], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, background: C.orange}} /></div><div style={{marginTop: 50, textAlign: 'center', ...inView(165)}}><Chip bg={C.green} style={{fontSize: 38}}>选择平均，不等于选择平庸</Chip></div></Content></Frame>;

  if (kind === 16) return <Frame page={page} kicker="指数基金 · 核心逻辑" title="标普500凭啥这么厉害？" subtitle="其实就六个字，把“谁更强”交给时间筛选。" titleSize={96}><Content style={{top: 470}}><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', ...inView(20)}}><Chip bg={C.blue} style={{fontSize: 86, padding: '24px 52px', boxShadow: `12px 14px 0 ${C.orange}`}}>不去猜测市场</Chip></div><div style={{marginTop: 82, textAlign: 'center', ...inView(125)}}><Chip bg={C.green} style={{fontSize: 43, padding: '18px 42px'}}>市值加权 · 自动分散</Chip></div></Content></Frame>;

  if (kind === 17) return <Frame page={page} kicker="指数基金 · 自动运行" title={<>赢家变大权重，<Mark color={C.green}>弱者自动被替换</Mark></>} subtitle="你不需要押中下一家伟大公司，也能分享赢家的收益。" titleSize={86}><Content><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, ...inView(18)}}>{[['公司A', '64%', C.orange], ['公司B', '44%', C.blue], ['公司C', '25%', C.green], ['公司D', '14%', '#BDBDB7']].map(([label, value, color], index) => <Panel key={String(label)} style={{height: 160, display: 'flex', alignItems: 'center', gap: 20}}><div style={{width: 140, fontSize: 32, fontWeight: 950}}>{label}</div><div style={{flex: 1, height: 42, border: `3px solid ${C.ink}`, borderRadius: 12, overflow: 'hidden', background: '#E8E8E0'}}><div style={{height: '100%', width: value, background: color}} /></div><div style={{width: 90, fontSize: 29, fontWeight: 950}}>{value}</div></Panel>)}</div><div style={{marginTop: 50, display: 'flex', justifyContent: 'center', gap: 34, ...inView(100)}}><Chip bg={C.green} style={{fontSize: 34}}>厉害的公司不断变大</Chip><Chip bg={C.orange} style={{fontSize: 34}}>弱一点的公司自动退出</Chip></div></Content></Frame>;

  if (kind === 18) return <Frame page={page} kicker="巴菲特给妻子的信托" title={<>90%标普500 + <Mark color={C.blue}>10%短期国债</Mark></>} subtitle="简单配置，长期持有。" titleSize={88}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 95, ...inView(18)}}><div style={{width: 410, height: 410, borderRadius: '50%', border: `6px solid ${C.ink}`, background: `conic-gradient(${C.green} 0deg 324deg, ${C.blue} 324deg 360deg)`, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: `12px 14px 0 ${C.orange}`}}><div style={{width: 240, height: 240, borderRadius: '50%', background: C.paper, border: `4px solid ${C.ink}`, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center'}}><div style={{fontSize: 68, fontWeight: 950}}>90 / 10</div><div style={{fontSize: 25, fontWeight: 900}}>配置</div></div></div><div style={{display: 'flex', flexDirection: 'column', gap: 28}}><Chip bg={C.green} style={{fontSize: 42, padding: '18px 32px'}}>90% 标普500</Chip><Chip bg={C.blue} style={{fontSize: 42, padding: '18px 32px'}}>10% 短期国债</Chip></div></div></Content></Frame>;

  if (kind === 19) return <Frame page={page} kicker="普通人的好处" title={<>对普通人来说，<Mark color={C.orange}>指数有两大好处</Mark></>} subtitle="第一，把问题变简单；第二，成本更低。" titleSize={91}><Content><div style={{display: 'flex', justifyContent: 'center', gap: 42, ...inView(18)}}><Panel bg={C.paleGreen} shadow={`12px 14px 0 ${C.green}`} style={{width: 690, height: 320}}><div style={{fontSize: 68, fontWeight: 950, color: C.green}}>01</div><div style={{marginTop: 26, fontSize: 48, fontWeight: 950}}>把问题变简单</div></Panel><Panel bg={C.paleOrange} shadow={`12px 14px 0 ${C.orange}`} style={{width: 690, height: 320}}><div style={{fontSize: 68, fontWeight: 950, color: C.orange}}>02</div><div style={{marginTop: 26, fontSize: 48, fontWeight: 950}}>成本更低</div></Panel></div></Content></Frame>;

  if (kind === 20) return <Frame page={page} kicker="普通人的好处 · 01" title={<>第一，把问题<Mark color={C.green}>变简单</Mark></>} subtitle="选股要判断公司、管理层、估值；买指数，只需要相信国运。" titleSize={96}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 26, ...inView(18)}}>{['公司', '管理层', '估值'].map((x) => <Chip key={x} bg="#FFFDF7" style={{fontSize: 43, padding: '20px 30px'}}>{x}</Chip>)}<Arrow /><Chip bg={C.green} style={{fontSize: 46, padding: '20px 34px'}}>相信国运</Chip></div><div style={{marginTop: 70, textAlign: 'center', ...inView(120)}}><Chip bg={C.blue} style={{fontSize: 36}}>少做三个判断，少犯三类错误</Chip></div></Content></Frame>;

  if (kind === 21) return <Frame page={page} kicker="普通人的好处 · 02" title={<>第二，<Mark color={C.orange}>成本更低</Mark>，复利更有力量</>} subtitle="费率在买入之前就能锁定，每年少扣一点，长期下来就是天壤之别。" titleSize={80}><Content><div style={{height: 440, display: 'flex', alignItems: 'end', justifyContent: 'center', gap: 48, ...inView(18)}}>{[130, 190, 265, 355, 455].map((height, index) => <div key={height} style={{width: 160, height, border: `4px solid ${C.ink}`, borderRadius: '16px 16px 0 0', background: index === 4 ? C.green : C.blue, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28, fontWeight: 950, boxShadow: `7px 0 0 ${index === 4 ? C.orange : C.blue}`}}>{index + 1}年</div>)}</div><div style={{marginTop: 45, textAlign: 'center', ...inView(120)}}><Chip bg={C.orange} style={{fontSize: 39}}>小费率 × 长时间 = 巨大的差距</Chip></div></Content></Frame>;

  if (kind === 22) return <Frame page={page} kicker="风险提醒" title={<>最后先泼盆冷水：<Mark color={C.orange}>指数不消灭波动</Mark></>} subtitle="巴菲特自己也跌过50%。不能承受浮亏的钱，就别全放股市。" titleSize={82}><Content><Panel shadow={`12px 14px 0 ${C.blue}`} style={{height: 310, ...inView(18)}}><div style={{fontSize: 34, color: C.gray, fontWeight: 900}}>浮亏承受力</div><div style={{marginTop: 12, fontSize: 130, lineHeight: 1, fontWeight: 950, color: C.orange}}>-50%</div><div style={{position: 'absolute', left: 38, right: 38, bottom: 34, height: 23, borderRadius: 14, background: '#E3E3DC', overflow: 'hidden'}}><div style={{height: '100%', width: `${interpolate(frame, [30, 180], [0, 50], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'})}%`, background: C.orange}} /></div></Panel><div style={{marginTop: 48, textAlign: 'center', ...inView(130)}}><Chip bg={C.orange} style={{fontSize: 37}}>不能承受浮亏的钱，就别全放股市</Chip></div></Content></Frame>;

  if (kind === 23) return <Frame page={page} kicker="买之前再看两眼" title={<>买标普500之前，<Mark color={C.blue}>先看这两个东西</Mark></>} subtitle="我之前的视频已经讲过：场内溢价和跟踪误差。" titleSize={84}><Content><div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 34, ...inView(18)}}><Panel bg={C.paleGreen} shadow={`12px 14px 0 ${C.green}`} style={{height: 360}}><Chip>01</Chip><div style={{marginTop: 34, fontSize: 51, fontWeight: 950}}>场内溢价</div><div style={{marginTop: 24, fontSize: 31, color: C.gray, fontWeight: 800}}>价格可能比真实价值贵</div></Panel><Panel shadow={`12px 14px 0 ${C.blue}`} style={{height: 360}}><Chip bg={C.blue}>02</Chip><div style={{marginTop: 34, fontSize: 51, fontWeight: 950}}>跟踪误差</div><div style={{marginTop: 24, fontSize: 31, color: C.gray, fontWeight: 800}}>基金不一定完全跟住指数</div></Panel></div></Content></Frame>;

  if (kind === 24) return <Frame page={page} kicker="场内溢价" title={<>溢价太高，<Mark color={C.orange}>好指数也可能赚不到钱</Mark></>} subtitle="买入之前，先把价格和真实价值的距离看清楚。" titleSize={82}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 55, ...inView(18)}}><Panel style={{width: 560, height: 300, textAlign: 'center'}}><div style={{fontSize: 34, color: C.gray, fontWeight: 850}}>真实价值</div><div style={{marginTop: 30, fontSize: 78, fontWeight: 950}}>100</div></Panel><Arrow>＜</Arrow><Panel bg={C.paleOrange} shadow={`12px 14px 0 ${C.orange}`} style={{width: 560, height: 300, textAlign: 'center'}}><div style={{fontSize: 34, color: C.gray, fontWeight: 850}}>场内价格</div><div style={{marginTop: 30, fontSize: 78, fontWeight: 950, color: C.orange}}>120</div></Panel></div><div style={{marginTop: 58, textAlign: 'center', ...inView(110)}}><Chip bg={C.orange} style={{fontSize: 38}}>贵了再买，也会影响收益</Chip></div></Content></Frame>;

  if (kind === 25) return <Frame page={page} kicker="不知道怎么看溢价" title={<>实在不知道怎么看？<br /><Mark color={C.green}>就买场外的</Mark></>} subtitle="先把复杂的检查，交给更简单的入口。" titleSize={96}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', ...inView(18)}}><div style={{fontSize: 154, fontWeight: 950, color: C.green, letterSpacing: -7}}>买场外</div></div><div style={{marginTop: 65, textAlign: 'center', ...inView(100)}}><Chip bg={C.blue} style={{fontSize: 42, padding: '20px 40px'}}>把选择做简单</Chip></div></Content></Frame>;

  if (kind === 26) return <Frame page={page} kicker="轮到你了" title={<>你是<Mark color={C.orange}>主动选股</Mark>，还是被动指数？</>} subtitle="欢迎在评论区聊聊你的选择。" titleSize={80}><Content><div style={{display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 48, ...inView(18)}}><Chip bg={C.orange} style={{fontSize: 55, padding: '24px 48px'}}>主动选股</Chip><div style={{fontSize: 58, fontWeight: 950, color: C.gray}}>还是</div><Chip bg={C.green} style={{fontSize: 55, padding: '24px 48px'}}>被动指数</Chip></div><div style={{marginTop: 72, textAlign: 'center', ...inView(105)}}><Chip bg={C.blue} style={{fontSize: 35}}>你的答案是什么？</Chip></div></Content></Frame>;

  return <Frame page={page} kicker="结尾" title={<>别忘了<Mark color={C.orange}>点赞 · 收藏 · 关注</Mark></>} subtitle="下期见。" titleSize={100}><Content><div style={{display: 'flex', justifyContent: 'center', ...inView(20)}}><Chip bg={C.green} style={{fontSize: 53, padding: '24px 50px'}}>把复杂的投资，讲得更简单</Chip></div></Content></Frame>;
};

const Scene: React.FC<{kind: number; page: number}> = ({kind, page}) => <>
  <SceneSfx kind={kind} />
  <SceneVisual kind={kind} page={page} />
</>;

export const SrtBuffettVideo: React.FC = () => <AbsoluteFill style={{background: C.paper}}>
  <Audio src={staticFile('buffett-index-intro.mp3')} />
  {SCENE_STARTS.map((start, index) => <Sequence key={start} from={Math.round(start * 30)} durationInFrames={SCENE_FRAMES[index]} name={`字幕段 ${String(index + 1).padStart(2, '0')}`}><PageSfx page={index + 1} /><Scene kind={SCENE_KINDS[index]} page={index + 1} /></Sequence>)}
  <div style={{display: 'none'}}>{TOTAL_FRAMES}</div>
</AbsoluteFill>;
